In [7]:
import pandas as pd

In [2]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

countries.info()

---

<div class="alert alert-success">
    <b>EXERCISE 01</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

In [5]:
(countries['population']*1_000_000) / countries['area']

country
Belgium           370.370370
France             95.783158
Germany           227.699202
Netherlands       406.973944
United Kingdom    265.092721
dtype: float64

In [6]:
countries['density']=(countries['population']*1_000_000) / countries['area']
countries

                population    area    capital     density
country
Belgium               11.3   30510   Brussels  370.370370
France                64.3  671308      Paris   95.783158
Germany               81.3  357050     Berlin  227.699202
Netherlands           16.9   41526  Amsterdam  406.973944
United Kingdom        64.9  244820     London  265.092721

<div class="alert alert-success">
    <b>EXERCISE 02</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

In [7]:
countries[countries['density']>300] # countries에 조건 걸어놓고 전체 컬럼 출력

             population   area    capital     density
country
Belgium            11.3  30510   Brussels  370.370370
Netherlands        16.9  41526  Amsterdam  406.973944

In [8]:
countries.loc[countries['density']>300, ['capital','population']] # 특정 컬럼만 출력

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

<div class="alert alert-success">
    <b>EXERCISE 03</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

In [10]:
# density를 density평균으로 나누기
# 계산 후 컬럼 추가해주기
countries['density_ratio']= countries['density'] / countries['density'].mean() 
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 04</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

In [11]:
countries

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

In [12]:
# 'London'위치 찾고 새로운 값'Cambridge' 넣어주기
countries[countries['capital']=='London', 'capital']= 'Cambridge'

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

In [ ]:
countries.loc[United Kingdom]

<div class="alert alert-success">
    <b>EXERCISE 05</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

In [19]:
countries[countries['density']>100 & countries['density']<300]

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

<div class="alert alert-success">
    <b>EXERCISE 06</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

In [14]:
countries[countries['capital'].str.len() >= 7]

             population   area    capital     density  density_ratio
country
Belgium            11.3  30510   Brussels  370.370370       1.355755
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744

<div class="alert alert-success">
    <b>EXERCISE 07</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

In [20]:
countries[countries['capital'].str.contains('am')]

             population   area    capital     density  density_ratio
country
Netherlands        16.9  41526  Amsterdam  406.973944       1.489744

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

In [46]:
data=pd.read_csv("./data/movie_title_data.tsv", sep="\t")
data.head()

C:\Users\a\AppData\Local\Temp\ipykernel_11188\3810222516.py:1: DtypeWarning: Columns (0: isAdult, 1: startYear) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("./data/movie_title_data.tsv", sep="\t")

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,\N,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,\N,1,"Comedy,Short"

In [47]:
data.info(show_counts=True) # Non-Null Count까지 나옴

<class 'pandas.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   tconst          8407399 non-null  str
 1   titleType       8407399 non-null  str
 2   primaryTitle    8407385 non-null  str
 3   originalTitle   8407385 non-null  str
 4   isAdult         8407399 non-null  object
 5   startYear       8407399 non-null  object
 6   endYear         8407399 non-null  str
 7   runtimeMinutes  8407399 non-null  str
 8   genres          8407389 non-null  str
dtypes: object(2), str(7)
memory usage: 577.3+ MB

In [24]:
data.isna().sum()

tconst             0
titleType          0
primaryTitle      14
originalTitle     14
isAdult            0
startYear          0
endYear            0
runtimeMinutes     0
genres            10
dtype: int64

In [26]:
# '\\N'가 껴있는 거 있어서 처리해주어야 함

data.loc[data['startYear']=='\\N', 'startYear']=0
data['startYear'].astype(int)
# 이제 결과 숫자로만 나옴

0          1894
1          1892
2          1892
3          1892
4          1893
           ...
8407394    2010
8407395    2010
8407396    2010
8407397    2015
8407398    2014
Name: startYear, Length: 8407399, dtype: int64

In [27]:
data['startYear']=data['startYear'].astype(int)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          str
 1   titleType       str
 2   primaryTitle    str
 3   originalTitle   str
 4   isAdult         object
 5   startYear       int64
 6   endYear         str
 7   runtimeMinutes  str
 8   genres          str
dtypes: int64(1), object(1), str(7)
memory usage: 577.3+ MB

In [29]:
data['endYear']=data['endYear'].str.replace('\\N','0')
data['endYear']=data['endYear'].astype(int)
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          str
 1   titleType       str
 2   primaryTitle    str
 3   originalTitle   str
 4   isAdult         object
 5   startYear       int64
 6   endYear         int64
 7   runtimeMinutes  str
 8   genres          str
dtypes: int64(2), object(1), str(6)
memory usage: 577.3+ MB

- 'runtimeMinutes' 숫자로 바꾸기

In [43]:
data['runtimeMinutes'].unique()

<StringArray>
[   '1',    '5',    '4',   '12',   '40',    '2',   '\N',    '0',    '3',
   '20',
 ...
 '1750',  '808', '1980', '2112',  '716',  '690',  '755',  '721',  '424',
 '2088']
Length: 856, dtype: str

In [44]:
data['runtimeMinutes']=data['runtimeMinutes'].str.replace('\\n','0')

In [45]:
# 반복문으로 넣는 방법 - 복잡함, 잘 안 함
result=[]
for row in data['runtimeMinutes']:
    try:
        temp=int(row)
        result.append(temp)
    except:
        result.append(0)
result

[1,
 5,
 4,
 12,
 1,
 1,
 1,
 1,
 40,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 1,
 2,
 0,
 1,
 1,
 0,
 0,
 20,
 0,
 0,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 3,
 0,
 1,
 0,
 0,
 0,
 0,
 13,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 6,
 1,
 0,
 2,
 1,
 1,
 0,
 0,
 0,
 2,
 1,
 0,
 3,
 0,
 0,
 0,
 1,
 5,
 1,
 0,
 3,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 4,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 2,
 1,
 1,
 0,
 2,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 1,
 6,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 40,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 1,
 0,
 0,
 4,
 0,
 5,
 0,
 2,
 5,
 3,
 0,
 0,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 3,
 6,
 0,
 0,
 11,
 0,
 0,
 0,
 3,
 0,
 6,
 0,
 0,
 9,
 6,
 3,
 0,
 0,
 4,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 10,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 2,
 0,
 0,
 3,
 2,
 0,
 4,
 13,
 0,
 0,
 8,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 11,
 4,
 0,
 0,
 15,
 0,
 0,
 21,
 6,
 0,
 0,
 0,
 4,
 2,
 0,
 0,
 3,
 0,
 0,
 0,
 2,
 15,
 0,
 0,
 1,
 4,
 16,
 0,
 0,
 0,
 1,
 0,
 13,
 0,
 0,
 0,
 10,
 0,
 0,
 0,
 4,
 3,
 0,
 0,
 0,
 0,
 0,
 5,
 12,
 14,
 0,
 0,
 1,
 6,
 0,
 0,
 12,
 0,
 5,
 7,
 24,
 0,
 0,
 100,
 2,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 10,
 4,
 0,
 0,
 6,
 8,
 0,
 0,
 8,
 14,
 12,
 0,
 0,
 6,
 7,
 0,
 0,
 15,
 0,
 0,
 0,
 0,
 0,
 3,
 4,
 6,
 4,
 0,
 0,
 0,
 6,
 7,
 15,
 0,
 0,
 7,
 0,
 0,
 0,
 3,
 0,
 2,
 5,
 3,
 7,
 0,
 15,
 0,
 3,
 0,
 13,
 0,
 0,
 0,
 9,
 5,
 17,
 0,
 0,
 3,
 14,
 7,
 0,
 70,
 10,
 13,
 0,
 0,
 0,
 3,
 0,
 15,
 0,
 8,
 6,
 0,
 0,
 0,
 0,
 10,
 90,
 0,
 0,
 0,
 9,
 0,
 7,
 10,
 0,
 0,
 10,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 6,
 0,
 9,
 0,
 0,
 0,
 20,
 0,
 0,
 6,
 20,
 0,
 0,
 6,
 0,
 0,
 12,
 17,
 0,
 0,
 14,
 0,
 0,
 0,
 15,
 9,
 7,
 12,
 12,
 12,
 0,
 9,
 9,
 0,
 0,
 10,
 0,
 0,
 5,
 12,
 16,
 12,
 0,
 10,
 2,
 10,
 11,
 0,
 0,
 17,
 6,
 11,
 25,
 9,
 14,
 10,
 12,
 0,
 10,
 15,
 15,
 0,
 0,
 0,
 0,
 120,
 0,
 0,
 2,
 14,
 10,
 15,
 0,
 0,
 0,
 9,
 8,
 0,
 0,
 0,
 14,
 17,
 9,
 15,
 15,
 15,
 6,
 0,
 0,
 0,
 36,
 13,
 15,
 12,
 13,
 0,
 0,
 0,
 0,
 17,
 0,
 9,
 0,
 14,
 13,
 0,
 0,
 18,
 9,
 0,
 10,
 7,
 11,
 0,
 8,
 11,
 0,
 10,
 0,
 0,
 13,
 0,
 0,
 16,
 14,
 0,
 0,
 0,
 0,
 8,
 17,
 14,
 8,
 0,
 0,
 10,
 0,
 0,
 4,
 11,
 0,
 0,
 0,
 0,
 7,
 8,
 0,
 11,
 0,
 0,
 11,
 0,
 6,
 17,
 7,
 13,
 0,
 0,
 0,
 17,
 0,
 0,
 13,
 0,
 0,
 8,
 10,
 0,
 9,
 0,
 11,
 0,
 13,
 11,
 0,
 4,
 0,
 0,
 0,
 0,
 11,
 0,
 0,
 8,
 11,
 0,
 0,
 0,
 0,
 0,
 11,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 11,
 11,
 0,
 0,
 10,
 0,
 11,
 24,
 11,
 0,
 4,
 6,
 10,
 11,
 11,
 12,
 9,
 14,
 14,
 0,
 10,
 16,
 10,
 0,
 0,
 13,
 8,
 0,
 11,
 0,
 7,
 0,
 10,
 0,
 0,
 0,
 10,
 13,
 7,
 7,
 7,
 30,
 6,
 11,
 0,
 5,
 11,
 0,
 0,
 5,
 0,
 0,
 0,
 0,
 0,
 11,
 11,
 0,
 0,
 4,
 8,
 0,
 6,
 6,
 0,
 15,
 0,
 5,
 14,
 0,
 19,
 0,
 0,
 0,
 0,
 0,
 3,
 6,
 0,
 0,
 10,
 10,
 5,
 11,
 0,
 3,
 6,
 6,
 11,
 16,
 4,
 0,
 10,
 11,
 5,
 11,
 4,
 11,
 0,
 7,
 0,
 6,
 5,
 0,
 11,
 5,
 6,
 4,
 0,
 5,
 0,
 0,
 0,
 16,
 0,
 0,
 0,
 0,
 8,
 11,
 11,
 11,
 2,
 11,
 0,
 0,
 8,
 5,
 0,
 5,
 6,
 0,
 0,
 0,
 0,
 0,
 7,
 0,
 0,
 0,
 9,
 20,
 5,
 0,
 11,
 10,
 3,
 0,
 6,
 0,
 12,
 7,
 0,
 44,
 20,
 6,
 11,
 10,
 4,
 5,
 0,
 0,
 0,
 0,
 11,
 0,
 2,
 0,
 8,
 10,
 0,
 2,
 3,
 14,
 0,
 0,
 3,
 0,
 10,
 0,
 11,
 12,
 0,
 7,
 11,
 6,
 8,
 8,
 4,
 10,
 0,
 0,
 5,
 0,
 5,
 ...]

In [49]:
# 반복문 안 하고 함수 짜기!!
def str2int(text):
    try:
        temp=int(text)
        return temp
    except:
        return 0

In [51]:
data['runtimeMinutes']=data['runtimeMinutes'].apply(str2int)

In [55]:
data['startYear']=data['startYear'].apply(str2int)

In [56]:
data['endYear']=data['endYear'].apply(str2int)

In [57]:
data['isAdult']=data['isAdult'].apply(str2int)

In [58]:
data.info()
# 함수 하나 만들고 apply 사용하면 편하게 형변환 가능
# runtimeMinutes, startYear,..등 - int64로 잘 바뀜

<class 'pandas.DataFrame'>
RangeIndex: 8407399 entries, 0 to 8407398
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          str
 1   titleType       str
 2   primaryTitle    str
 3   originalTitle   str
 4   isAdult         int64
 5   startYear       int64
 6   endYear         int64
 7   runtimeMinutes  int64
 8   genres          str
dtypes: int64(4), str(5)
memory usage: 577.3 MB

In [19]:
# print(type(titles[titles['startYear'].isna()]['startYear'][0]))

In [20]:
# titles['startYear'] = titles['startYear'].astype("float16")
# titles['startYear']

<div class="alert alert-success">
    <b>EXERCISE 08</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

In [31]:
data.drop_duplicates()
# 중복 제거하고 1개씩만 남김

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0,1894,0,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0,1892,0,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0,1892,0,4,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0,1892,0,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0,1893,0,1,"Comedy,Short"
...,...,...,...,...,...,...,...,...,...
8407394,tt9916848,tvEpisode,Episode #3.17,Episode #3.17,0,2010,0,\N,"Action,Drama,Family"
8407395,tt9916850,tvEpisode,Episode #3.19,Episode #3.19,0,2010,0,\N,"Action,Drama,Family"
8407396,tt9916852,tvEpisode,Episode #3.20,Episode #3.20,0,2010,0,\N,"Action,Drama,Family"
8407397,tt9916856,short,The Wind,The Wind,0,2015,0,27,Short
8407398,tt9916880,tvEpisode,Horrid Henry Knows It All,Horrid Henry Knows It All,0,2014,0,10,"Adventure,Animation,Comedy"

In [32]:
len(data.drop_duplicates())

8407399

<div class="alert alert-success">
    <b>EXERCISE 09</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

In [35]:
# startYear 0인거 제외한 후 오름차순에서 가장 처음 2개
data[data['startYear']>0].sort_values(by='startYear').head(2)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
5329521,tt3155794,short,Passage de Venus,Passage de Venus,0,1874,0,1,"Documentary,Short"
3488807,tt14495706,short,La Rosace Magique,La Rosace Magique,0,1877,0,1,"Animation,Short"

<div class="alert alert-success">
    <b>EXERCISE 10</b>: 제목(title)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

In [37]:
# 제목이 정확히 "Hamlet"인 것 찾기
data[data['originalTitle']=='Hamlet']

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
594,tt0000598,short,"Hamlet, Prince of Denmark",Hamlet,0,1907,0,10,"Drama,Short"
876,tt0000886,movie,"Hamlet, Prince of Denmark",Hamlet,0,1910,0,\N,Drama
1228,tt0001240,movie,Hamlet,Hamlet,0,1911,0,\N,Drama
1229,tt0001241,short,Hamlet,Hamlet,0,1910,0,20,"Drama,Short"
1230,tt0001242,short,Hamlet,Hamlet,0,1908,0,\N,"Drama,Short"
...,...,...,...,...,...,...,...,...,...
7347169,tt7656792,tvEpisode,Hamlet,Hamlet,0,2017,0,\N,Animation
7413345,tt7798632,movie,Hamlet,Hamlet,0,0,0,\N,Comedy
7476376,tt7934018,tvMovie,Hamlet,Hamlet,0,1983,0,\N,Drama
7609545,tt8219328,tvMovie,Hamlet,Hamlet,0,2018,0,191,Drama
8306453,tt9703966,movie,Hamlet,Hamlet,0,0,0,\N,Drama

In [38]:
# 'Hamlet'이 들어있는 제목 모두 찾기
data[data['originalTitle'].str.contains('Hamlet')]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
303,tt0000306,short,Le duel d'Hamlet,Le duel d'Hamlet,0,1900,0,2,"Drama,Short"
594,tt0000598,short,"Hamlet, Prince of Denmark",Hamlet,0,1907,0,10,"Drama,Short"
876,tt0000886,movie,"Hamlet, Prince of Denmark",Hamlet,0,1910,0,\N,Drama
1228,tt0001240,movie,Hamlet,Hamlet,0,1911,0,\N,Drama
1229,tt0001241,short,Hamlet,Hamlet,0,1910,0,20,"Drama,Short"
...,...,...,...,...,...,...,...,...,...
8114427,tt9297654,video,Ten Deaths of Hamlet,Ten Deaths of Hamlet,0,2018,0,\N,Drama
8182008,tt9440248,movie,Hamlet Shakespeare's Globe,Hamlet Shakespeare's Globe,0,2018,0,154,Drama
8235329,tt9553644,tvEpisode,Hamlet Stanislawa Wyspianskiego,Hamlet Stanislawa Wyspianskiego,0,2008,0,63,Drama
8306453,tt9703966,movie,Hamlet,Hamlet,0,0,0,\N,Drama
8400053,tt9901352,movie,Hamlet Poem Unlimited,Hamlet Poem Unlimited,0,2018,0,60,Drama

In [39]:
len(data[data['originalTitle'].str.contains('Hamlet')])

417

<div class="alert alert-success">
    <b>EXERCISE 11</b>: 제목(title)이 "Treasure Island"인 영화를 제작년도(year)의 오름차순에 따라 표시하세요
</div>

In [41]:
data[(data['originalTitle']=='Treasure Island') & (data['startYear']>0)].sort_values(by='startYear')

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
2511,tt0002538,short,Treasure Island,Treasure Island,0,1912,0,\N,"Adventure,Short"
5032142,tt2440348,short,Treasure Island,Treasure Island,0,1913,0,\N,"Short,Thriller"
9589,tt0009721,movie,Treasure Island,Treasure Island,0,1917,0,60,Adventure
11620,tt0011785,movie,Treasure Island,Treasure Island,0,1920,0,76,Adventure
25459,tt0025907,movie,Treasure Island,Treasure Island,0,1934,0,110,"Adventure,Family"
...,...,...,...,...,...,...,...,...,...
7423990,tt7821190,tvEpisode,Treasure Island,Treasure Island,0,2018,0,\N,"Action,Adventure,Animation"
2208762,tt12185946,tvEpisode,Treasure Island,Treasure Island,0,2019,0,\N,\N
1431503,tt10815740,tvEpisode,Treasure Island,Treasure Island,0,2019,0,\N,Comedy
6917550,tt6727462,tvEpisode,Treasure Island,Treasure Island,0,2019,0,71,"Drama,Fantasy,Mystery"
3809301,tt15075064,tvEpisode,Treasure Island,Treasure Island,0,2021,0,\N,"Animation,Comedy"

<div class="alert alert-success">
    <b>EXERCISE 12</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

In [42]:
len(data[(data['startYear']>=1950) & (data['startYear']<=1959)])

118649

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

In [6]:
import os
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()
from dotenv import load_dotenv
load_dotenv()

True

In [8]:
import pandas as pd

In [2]:
dbid=os.getenv("dbid2")
dbpw=os.getenv("dbpw2")
host=os.getenv("host2")
port=os.getenv("port2")
dbname=os.getenv("dbname")

In [52]:
# 접속하기
engine=create_engine(f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}/{dbname}")
conn=engine.connect()

In [53]:
# 테이블 불러오기
table1 = pd.read_sql("p_info", con=conn)
table2 = pd.read_sql("t_info", con=conn)
table3 = pd.read_sql("survived", con=conn)

In [54]:
table1

,PassengerId,Name,Sex,Age,SibSp,Parch
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0

In [55]:
table2

     PassengerId            Ticket  Pclass     Fare Cabin Embarked
0              1         A/5 21171       3   7.2500   NaN        S
1              2          PC 17599       1  71.2833   C85        C
2              3  STON/O2. 3101282       3   7.9250   NaN        S
3              4            113803       1  53.1000  C123        S
4              5            373450       3   8.0500   NaN        S
..           ...               ...     ...      ...   ...      ...
886          887            211536       2  13.0000   NaN        S
887          888            112053       1  30.0000   B42        S
888          889        W./C. 6607       3  23.4500   NaN        S
889          890            111369       1  30.0000  C148        C
890          891            370376       3   7.7500   NaN        Q

[891 rows x 6 columns]

In [56]:
table3

     PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

- 테이블1,2,3 합치기 - merge

In [57]:
merged_table=pd.merge(table1, table2, how="inner", on="PassengerId")
merged_table

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q

In [58]:
df=pd.merge(merged_table, table3, how="inner", on="PassengerId")
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0

<div class="alert alert-success">
    <b>EXERCISE 13</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

In [16]:
df.head()

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 14</b>: 데이터의 정보(info)를 출력하세요.
</div>

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    str
 2   Sex          891 non-null    str
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Ticket       891 non-null    str
 7   Pclass       891 non-null    int64
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    str
 10  Embarked     889 non-null    str
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

<div class="alert alert-success">
    <b>EXERCISE 15</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

In [18]:
df.describe()

,PassengerId,Age,SibSp,Parch,Pclass,Fare,Survived
count,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,29.699118,0.523008,0.381594,2.308642,32.204208,0.383838
std,257.353842,14.526497,1.102743,0.806057,0.836071,49.693429,0.486592
min,1.000000,0.420000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,223.500000,20.125000,0.000000,0.000000,2.000000,7.910400,0.000000
50%,446.000000,28.000000,0.000000,0.000000,3.000000,14.454200,0.000000
75%,668.500000,38.000000,1.000000,0.000000,3.000000,31.000000,1.000000
max,891.000000,80.000000,8.000000,6.000000,3.000000,512.329200,1.000000

<div class="alert alert-success">
    <b>EXERCISE 16</b>: 처음 100명의 데이터를 출력하세요.
</div>

In [19]:
pd.set_option('display.max_rows', 100)

In [20]:
df.head(100)

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,3,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.00,0,0,373450,3,8.0500,NaN,S,0
5,6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,NaN,Q,0
6,7,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,1,51.8625,E46,S,0
7,8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,3,21.0750,NaN,S,0
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,3,11.1333,NaN,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,2,30.0708,NaN,C,1
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,3,16.7000,G6,S,1
11,12,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,1,26.5500,C103,S,1
12,13,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,3,8.0500,NaN,S,0
13,14,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,3,31.2750,NaN,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,3,7.8542,NaN,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,2,16.0000,NaN,S,1
16,17,"Rice, Master. Eugene",male,2.00,4,1,382652,3,29.1250,NaN,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,NaN,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.00,1,0,345763,3,18.0000,NaN,S,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,NaN,C,1
20,21,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,2,26.0000,NaN,S,0
21,22,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,2,13.0000,D56,S,1
22,23,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,3,8.0292,NaN,Q,1
23,24,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,1,35.5000,A6,S,1
24,25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,3,21.0750,NaN,S,0
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.00,1,5,347077,3,31.3875,NaN,S,1
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,NaN,C,0
27,28,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,1,263.0000,C23 C25 C27,S,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,NaN,Q,1
29,30,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,3,7.8958,NaN,S,0
30,31,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,1,27.7208,NaN,C,0
31,32,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,1,146.5208,B78,C,1
32,33,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,3,7.7500,NaN,Q,1
33,34,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,2,10.5000,NaN,S,0
34,35,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,1,82.1708,NaN,C,0
35,36,"Holverson, Mr. Alexander Oskar",male,42.00,1,0,113789,1,52.0000,NaN,S,0
36,37,"Mamee, Mr. Hanna",male,NaN,0,0,2677,3,7.2292,NaN,C,1
37,38,"Cann, Mr. Ernest Charles",male,21.00,0,0,A./5. 2152,3,8.0500,NaN,S,0
38,39,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,3,18.0000,NaN,S,0
39,40,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,3,11.2417,NaN,C,1
40,41,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,3,9.4750,NaN,S,0
41,42,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.00,1,0,11668,2,21.0000,NaN,S,0
42,43,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,3,7.8958,NaN,C,0
43,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,2,41.5792,NaN,C,1
44,45,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,3,7.8792,NaN,Q,1
45,46,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,3,8.0500,NaN,S,0
46,47,"Lennon, Mr. Denis",male,NaN,1,0,370371,3,15.5000,NaN,Q,0
47,48,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,3,7.7500,NaN,Q,1
48,49,"Samaan, Mr. Youssef",male,NaN,2,0,2662,3,21.6792,NaN,C,0
49,50,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.00,1,0,349237,3,17.8000,NaN,S,0
50,51,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,3,39.6875,NaN,S,0
51,52,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,3,7.8000,NaN,S,0
52,53,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,1,76.7292,D33,C,1
53,54,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.00,1,0,2926,2,26.0000,NaN,S,1
54,55,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,1,61.9792,B30,C,0
55,56,"Woolner, Mr. Hugh",male,NaN,0,0,19947,1,35.5000,C52,S,1
56,57,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,2,10.5000,NaN,S,1
57,58,"Novel, Mr. Mansouer",male,28.50,0,0,2697,3,7.2292,NaN,C,0
58,59,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,2,27.7500,NaN,S,1
59,60,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,3,46.9000,NaN,S,0
60,61,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,3,7.2292,NaN,C,0
61,62,"Icard, Miss. Amelie",female,38.00,0,0,113572,1,80.0000,B28,NaN,1
62,63,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,1,83.4750,C83,S,0
63,64,"Skoog, Master. Harald",male,4.00,3,2,347088,3,27.9000,NaN,S,0
64,65,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,1,27.7208,NaN,C,0
65,66,"Moubarek, Master. Gerios",male,NaN,1,1,2661,3,15.2458,NaN,C,1
66,67,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,2,10.5000,F33,S,1
67,68,"Crease, Mr. Ernest James",male,19.00,0,0,S.P. 3464,3,8.1583,NaN,S,0
68,69,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,3,7.9250,NaN,S,1
69,70,"Kink, Mr. Vincenz",male,26.00,2,0,315151,3,8.6625,NaN,S,0
70,71,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,2,10.5000,NaN,S,0
71,72,"Goodwin, Miss. Lillian Amy",female,16.00,5,2,CA 2144,3,46.9000,NaN,S,0
72,73,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,2,73.5000,NaN,S,0
73,74,"Chronopoulos, Mr. Apostolos",male,26.00,1,0,2680,3,14.4542,NaN,C,0
74,75,"Bing, Mr. Lee",male,32.00,0,0,1601,3,56.4958,NaN,S,1
75,76,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,3,7.6500,F G73,S,0
76,77,"Staneff, Mr. Ivan",male,NaN,0,0,349208,3,7.8958,NaN,S,0
77,78,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,3,8.0500,NaN,S,0
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,NaN,S,1
79,80,"Dowdell, Miss. Elizabeth",female,30.00,0,0,364516,3,12.4750,NaN,S,1
80,81,"Waelens, Mr. Achille",male,22.00,0,0,345767,3,9.0000,NaN,S,0
81,82,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,3,9.5000,NaN,S,1
82,83,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,3,7.7875,NaN,Q,1
83,84,"Carrau, Mr. Francisco M",male,28.00,0,0,113059,1,47.1000,NaN,S,0
84,85,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,2,10.5000,NaN,S,1
85,86,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.00,3,0,3101278,3,15.8500,NaN,S,1
86,87,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,3,34.3750,NaN,S,0
87,88,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,3,8.0500,NaN,S,0
88,89,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,1,263.0000,C23 C25 C27,S,1
89,90,"Celotti, Mr. Francesco",male,24.00,0,0,343275,3,8.0500,NaN,S,0
90,91,"Christmann, Mr. Emil",male,29.00,0,0,343276,3,8.0500,NaN,S,0
91,92,"Andreasson, Mr. Paul Edvin",male,20.00,0,0,347466,3,7.8542,NaN,S,0
92,93,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,1,61.1750,E31,S,0
93,94,"Dean, Mr. Bertram Frank",male,26.00,1,2,C.A. 2315,3,20.5750,NaN,S,0
94,95,"Coxon, Mr. Daniel",male,59.00,0,0,364500,3,7.2500,NaN,S,0
95,96,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,3,8.0500,NaN,S,0
96,97,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,1,34.6542,A5,C,0
97,98,"Greenfield, Mr. William Bertram",male,23.00,0,1,PC 17759,1,63.3583,D10 D12,C,1
98,99,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,2,23.0000,NaN,S,1
99,100,"Kantor, Mr. Sinai",male,34.00,1,0,244367,2,26.0000,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 17</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

In [21]:
# loc(인덱스이름) / iloc(인덱스번호)

df.loc[10:20, :] # 컬럼은 전부 다 -> : 만 씀

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,3,16.7000,G6,S,1
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
12,13,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,3,8.0500,NaN,S,0
13,14,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,3,31.2750,NaN,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,3,7.8542,NaN,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,2,16.0000,NaN,S,1
16,17,"Rice, Master. Eugene",male,2.0,4,1,382652,3,29.1250,NaN,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,NaN,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,3,18.0000,NaN,S,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,NaN,C,1
20,21,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,2,26.0000,NaN,S,0

In [22]:
df.iloc[10:21, :]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,3,16.7000,G6,S,1
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
12,13,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,3,8.0500,NaN,S,0
13,14,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,3,31.2750,NaN,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,3,7.8542,NaN,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,2,16.0000,NaN,S,1
16,17,"Rice, Master. Eugene",male,2.0,4,1,382652,3,29.1250,NaN,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,NaN,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,3,18.0000,NaN,S,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,NaN,C,1
20,21,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,2,26.0000,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

In [23]:
df.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Pclass', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='str')

<div class="alert alert-success">
    <b>EXERCISE 18</b>: 데이터의 shape를 확인하세요.
</div>

In [24]:
df.shape

(891, 12)

<div class="alert alert-success">
    <b>EXERCISE 19</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

In [25]:
df['Age'].mean()

np.float64(29.69911764705882)

<div class="alert alert-success">
    <b>EXERCISE 20</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

In [27]:
df['Survived'].unique()

array([0, 1])

<div class="alert alert-success">
    <b>EXERCISE 21</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

In [28]:
df[df['Age']>=30]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,1,51.8625,E46,S,0
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,3,9.0000,NaN,S,0
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
881,882,"Markun, Mr. Johann",male,33.0,0,0,349257,3,7.8958,NaN,S,0
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,3,29.1250,NaN,Q,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0

<div class="alert alert-success">
    <b>EXERCISE 22</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

In [29]:
df[(df['Sex']=="female") & (df['Survived']==1)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,3,11.1333,NaN,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,2,30.0708,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,2,24.0000,NaN,C,1
875,876,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,3,7.2250,NaN,C,1
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,2,26.0000,NaN,S,1
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1

<div class="alert alert-success">
    <b>EXERCISE 23</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

In [30]:
df[(df['Age']<=10) & (df['Fare']>=20)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
7,8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,3,21.0750,NaN,S,0
16,17,"Rice, Master. Eugene",male,2.00,4,1,382652,3,29.1250,NaN,Q,0
24,25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,3,21.0750,NaN,S,0
43,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,2,41.5792,NaN,C,1
50,51,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,3,39.6875,NaN,S,0
58,59,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,2,27.7500,NaN,S,1
63,64,"Skoog, Master. Harald",male,4.00,3,2,347088,3,27.9000,NaN,S,0
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,NaN,S,1
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,3,31.2750,NaN,S,0
147,148,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,3,34.3750,NaN,S,0
164,165,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,3,39.6875,NaN,S,0
165,166,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,3,20.5250,NaN,S,1
171,172,"Rice, Master. Arthur",male,4.00,4,1,382652,3,29.1250,NaN,Q,0
182,183,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,3,31.3875,NaN,S,0
183,184,"Becker, Master. Richard F",male,1.00,2,1,230136,2,39.0000,F4,S,1
184,185,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,3,22.0250,NaN,S,1
193,194,"Navratil, Master. Michel M",male,3.00,1,1,230080,2,26.0000,F2,S,1
233,234,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,3,31.3875,NaN,S,1
237,238,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,2,26.2500,NaN,S,1
261,262,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,3,31.3875,NaN,S,1
278,279,"Rice, Master. Eric",male,7.00,4,1,382652,3,29.1250,NaN,Q,0
297,298,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,1,151.5500,C22 C26,S,0
305,306,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,1,151.5500,C22 C26,S,1
340,341,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,2,26.0000,F2,S,1
374,375,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,3,21.0750,NaN,S,0
386,387,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,3,46.9000,NaN,S,0
419,420,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,3,24.1500,NaN,S,0
445,446,"Dodge, Master. Washington",male,4.00,0,2,33638,1,81.8583,A34,S,1
480,481,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,3,46.9000,NaN,S,0
530,531,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,2,26.0000,NaN,S,1
535,536,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,2,26.2500,NaN,S,1
541,542,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,3,31.2750,NaN,S,0
549,550,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,2,36.7500,NaN,S,1
618,619,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,2,39.0000,F4,S,1
634,635,"Skoog, Miss. Mabel",female,9.00,3,2,347088,3,27.9000,NaN,S,0
642,643,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,3,27.9000,NaN,S,0
720,721,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,2,33.0000,NaN,S,1
750,751,"Wells, Miss. Joan",female,4.00,1,1,29103,2,23.0000,NaN,S,1
787,788,"Rice, Master. George Hugh",male,8.00,4,1,382652,3,29.1250,NaN,Q,0
788,789,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,3,20.5750,NaN,S,1
813,814,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,3,31.2750,NaN,S,0
819,820,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,3,27.9000,NaN,S,0
824,825,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,3,39.6875,NaN,S,0
827,828,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,2,37.0042,NaN,C,1
850,851,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,3,31.2750,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 24</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

In [31]:
df[df['Age'].isna()]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
5,6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,NaN,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,NaN,S,1
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,NaN,C,1
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,NaN,C,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,NaN,Q,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,NaN,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,NaN,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,NaN,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,NaN,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 25</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

In [32]:
df.sort_values(by='Age')

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
803,804,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,3,8.5167,NaN,C,1
755,756,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,2,14.5000,NaN,S,1
644,645,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,3,19.2583,NaN,C,1
469,470,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,3,19.2583,NaN,C,1
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,NaN,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,NaN,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,NaN,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,NaN,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 26</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

In [33]:
df.sort_values(by='Fare', ascending=False).head()

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
679,680,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,1,512.3292,B51 B53 B55,C,1
258,259,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,1,512.3292,NaN,C,1
737,738,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,1,512.3292,B101,C,1
88,89,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,1,263.0000,C23 C25 C27,S,1
438,439,"Fortune, Mr. Mark",male,64.0,1,4,19950,1,263.0000,C23 C25 C27,S,0

<div class="alert alert-success">
    <b>EXERCISE 27</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

In [35]:
df[['Sex', "Survived"]].groupby('Sex').mean()
# 보고 싶은 컬럼만 잘라와서 -> 그룹화하기

        Survived
Sex
female  0.742038
male    0.188908

<div class="alert alert-success">
    <b>EXERCISE 28</b>: Pclass별 평균 나이를 구하세요.
</div>

In [36]:
df[['Pclass', 'Age']].groupby('Pclass').mean()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

<div class="alert alert-success">
    <b>EXERCISE 29</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

In [40]:
df['Age_plus_10'] = df['Age'] + 10
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult,Age_plus_10
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0,성인,32.0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,성인,48.0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1,성인,36.0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,성인,45.0
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0,성인,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S,0,성인,37.0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,성인,29.0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0,미성년,NaN
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,성인,36.0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0,성인,42.0

<div class="alert alert-success">
    <b>EXERCISE 30</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

In [37]:
# 먼저 성인인지 미성년인지 구분하기
# 조건표현식 사용하기!

df['Age'].apply(lambda x:'성인' if x>=18 else '미성년')

0       성인
1       성인
2       성인
3       성인
4       성인
      ...
886     성인
887     성인
888    미성년
889     성인
890     성인
Name: Age, Length: 891, dtype: str

In [39]:
df['isadult']=df['Age'].apply(lambda x:'성인' if x>=18 else '미성년')
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,성인
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,성인
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S,0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0,미성년
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,성인
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0,성인

<div class="alert alert-success">
    <b>EXERCISE 31</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

- 아래 세 줄 중요함!

In [59]:
na_idx = df[df['Age'].isna()].index # 나이 결측치 부분 필터링하고 인덱스

In [60]:
# 나이 열에서 결측치 부분 -> 나이 평균으로 채우기
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [61]:
df.loc[na_idx] # 나이 결측치였던 행만 출력

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
5,6,"Moran, Mr. James",male,29.699118,0,0,330877,3,8.4583,NaN,Q,0
17,18,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,2,13.0000,NaN,S,1
19,20,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,3,7.2250,NaN,C,1
26,27,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,3,7.2250,NaN,C,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,3,7.8792,NaN,Q,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,29.699118,0,0,2629,3,7.2292,NaN,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,3,69.5500,NaN,S,0
868,869,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,3,9.5000,NaN,S,0
878,879,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,3,7.8958,NaN,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 32</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

In [63]:
cabin_nan_idx = df[df['Cabin'].isna()].index

In [64]:
df['Cabin'] = df['Cabin'].fillna("Unknown")

In [65]:
df.loc[cabin_nan_idx]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0
5,6,"Moran, Mr. James",male,29.699118,0,0,330877,3,8.4583,Unknown,Q,0
7,8,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,3,21.0750,Unknown,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,3,7.0500,Unknown,S,0
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0

<div class="alert alert-success">
    <b>EXERCISE 33</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

In [66]:
df[df['Ticket'].duplicated()]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
24,25,"Palsson, Miss. Torborg Danira",female,8.000000,3,1,349909,3,21.0750,Unknown,S,0
71,72,"Goodwin, Miss. Lillian Amy",female,16.000000,5,2,CA 2144,3,46.9000,Unknown,S,0
88,89,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,1,263.0000,C23 C25 C27,S,1
117,118,"Turpin, Mr. William John Robert",male,29.000000,1,0,11668,2,21.0000,Unknown,S,0
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.000000,4,2,347082,3,31.2750,Unknown,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
876,877,"Gustafsson, Mr. Alfred Ossian",male,20.000000,0,0,7534,3,9.8458,Unknown,S,0
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,1,83.1583,C50,C,1
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,2,26.0000,Unknown,S,1
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0

In [67]:
len(df.drop_duplicates(subset='Ticket'))

681

<div class="alert alert-success">
    <b>EXERCISE 34</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

In [68]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

<div class="alert alert-success">
    <b>EXERCISE 35</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

In [69]:
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0
889,890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0

In [70]:
df = df.set_index("PassengerId")
df

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1
3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1
5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0
888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0
890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1
891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0

In [73]:
df.index

RangeIndex(start=1, stop=892, step=1, name='PassengerId')

<div class="alert alert-success">
    <b>EXERCISE 36</b>: 인덱스를 초기화하세요.
</div>

In [74]:
df = df.reset_index()
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0
889,890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0

<div class="alert alert-success">
    <b>EXERCISE 37</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

In [75]:
df.pivot_table(values='Survived', index='Pclass', columns='Sex')

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

<div class="alert alert-success">
    <b>EXERCISE 38</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

In [76]:
df[['Sex', 'Age']].groupby('Sex').mean()

              Age
Sex
female  28.216730
male    30.505824

<div class="alert alert-success">
    <b>EXERCISE 39</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

In [77]:
df['Survived'].mean() * 100

np.float64(38.38383838383838)

<div class="alert alert-success">
    <b>EXERCISE 40</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [78]:
df.loc[df['Age'] <= 25, 'Survived'].mean() * 100

np.float64(41.19601328903654)

<div class="alert alert-success">
    <b>EXERCISE 41</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [79]:
print("남성의 생존율: ", df.loc[df['Sex'] == "male", "Survived"].mean())
print("여성의 생존율: ", df.loc[df['Sex'] == "female", "Survived"].mean())

남성의 생존율:  0.18890814558058924
여성의 생존율:  0.7420382165605095

<div class="alert alert-success">
    <b>EXERCISE 42</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구하기 위해 ?부분을 알맞게 채워주세요.
</div>

In [81]:
def survival_ratio(survived):
    return survived.sum() / len(survived)

In [82]:
df[['Sex', "Survived"]].groupby('Sex').agg(survival_ratio)
# 기존 있는 함수인 .mean() 외에도 
# 직접 만든 함수를 agg에 넣어서 값 수정 후 출력해줄 수 있음

        Survived
Sex
female  0.742038
male    0.188908