# pandas
[https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html)
- numpy를 내부적으로 활용함
- 데이터 분석에 특화된 데이터 구조 제공 (DataFrame, Series)
- 다양한 데이터 분석 함수 제공
- 데이터 베이스에 쉽게 연결 가능
- json, html의 table 요소를 DataFrame으로 쉽게 변경 가능

# 2.3 내용

In [1]:
# !pip install pandas

# pandas에서 다루는 데이터 타입 2가지
## 1) DataFrame : 2차원의 표 형식 데이터
- python의 dict와도 비슷
- 하나의 key에 list형태의 value가 매칭되어 있는 형태
```python
{key:[value1,value2,value3], key2:[value1,value2,value3]}
```

## 2) Series : 1차원의 벡터 형식 데이터
- python의 list, tuple, numpy의 ndarray와 비슷
- 이름이 있는 list

In [1]:
import pandas as pd

# 데이터프레임 만들기
```python
pd.DataFrame(
    {'이름' : ['홍길동','둘리','또치','도우너'],
     '주소' : ['서울','의정부','고양', '성남'],
     '취미' : ['음악감상', '놀기', '달리기','바이올린']
    })
df
```

In [3]:
df=pd.DataFrame(
    {'이름' : ['홍길동','둘리','또치','도우너'],
     '주소' : ['서울','의정부','고양', '성남'],
     '취미' : ['음악감상', '놀기', '달리기','바이올린']
    })
df

    이름   주소    취미
0  홍길동   서울  음악감상
1   둘리  의정부    놀기
2   또치   고양   달리기
3  도우너   성남  바이올린

In [4]:
# 딕셔너리 키 호출
df['이름'][2:3]

2    또치
Name: 이름, dtype: str

In [5]:
df.shape

(4, 3)

In [6]:
df.ndim

2

In [7]:
df.size

12

In [8]:
df['이름'].dtype

# Series 만들기
```python
pd.Series([리스트/튜플], name='컬럼명')
```
- 이름을 가지고 있는 list/ 벡터
- DataFrame에서 컬럼 1개를 잘라온 상태

In [9]:
ages = pd.Series([22,53,35], name='나이')
ages

0    22
1    53
2    35
Name: 나이, dtype: int64

In [10]:
ages[0]

np.int64(22)

In [11]:
ages[0:2:2]

0    22
Name: 나이, dtype: int64

In [12]:
ages[::-1]

2    35
1    53
0    22
Name: 나이, dtype: int64

In [13]:
ages.min()

np.int64(22)

In [14]:
ages.max()

np.int64(53)

In [15]:
ages.sum()

np.int64(110)

In [16]:
ages.cumsum() # 누적합

0     22
1     75
2    110
Name: 나이, dtype: int64

In [17]:
ages.mean()

np.float64(36.666666666666664)

In [18]:
ages.median()

np.float64(35.0)

# 판다스에서 자료 불러오기, 저장하기
- csv, tsv, excel, json, html, sql
- pd.read_확장자명(파일경로, 옵션)

- excel 파일 불러오기

In [19]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\a\miniforge3\envs\fintech\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\a\miniforge3\envs\fintech\lib\site-packages (from openpyxl) (2.0.0)

In [20]:
%%time
df_excel=pd.read_excel("./data/Online Retail.xlsx")
df_excel

KeyboardInterrupt:

- csv 파일 불러오기

In [21]:
%%time
df_csv=pd.read_csv("./data/Online Retail.csv")
df_csv # csv파일이 더 빠름, 용량도 더 큼

CPU times: total: 1.97 s
Wall time: 2.1 s

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [22]:
df_excel2=pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx", header=12)
df_excel2

# 엑셀 파일 안에 필요없는 정보가 위에 있음 -> 12번째 줄부터 필요함 - header=12 추가

C:\Users\a\miniforge3\envs\fintech\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [23]:
df_excel2.to_csv("./data/아파트(매매)_실거래가_20240806113828.csv", index=False, encoding="utf-8-sig)

SyntaxError: unterminated string literal (detected at line 1) (3982391976.py, line 1)

In [ ]:
%%time
df_csv2=pd.read_csv("./data/아파트(매매)_실거래가_20240806113828.csv")
df_csv2

In [ ]:
df_json=pd.read_json("./data/서울특별시_관광지입장정보_2011_2016.json")
df_json # json 파일 불러오기

In [ ]:
import json
with open("../03python/data/전국치킨집리스트.json") as f:
    df_json3=f.read()
    df_json3=json.loads(df_json3)

In [ ]:
df_json3[0]

In [ ]:
df_json2=pd.read_json("../03python/data/전국치킨집리스트.json") # 상대경로 이용해서 주소 찍기
df_json2
# json파일 읽어오기

In [ ]:
result=[]
for page in df_json3:
    temp_df = pd.json_normalize(page['body']['items'])
    result.append(temp_df)
final_result=pd.concat(result)
final_result

# 반복문 사용해서 굳이 하나하나 안 풀어도 되고
# pandas 이용하면 짧은 코드로 편리하게 표 형식 가능!!

In [ ]:
df_json2=pd.json_normalize(df_json3[0]['body']['items'])
df_json2

In [ ]:
df_html=pd.read_html("./data/corpList.htm")
df_html[0] # html파일 안에 데이터프레임 있으면 불러옴(1페이지)

# DB에서 자료 읽어오기

In [ ]:
import os
from dotenv import load_dotenv
load_dotenv("../05data_scraping/.env") # 하나 위로 올라가서 05data_scraping에서 .env 파일

In [ ]:
dbid = os.getenv("dbid")
dbpw = os.getenv("dbpw")
host = os.getenv("host")
port = os.getenv("port")

In [ ]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [ ]:
engine = create_engine(f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}/exchange_rage_data")
conn = engine.connect()
df_sql = pd.read_sql("exchage_rate", con=conn)
conn.close()
df_sql

# db에 접속한 후 테이블 이름만 적어주면 바로 가져올 수 있음

In [ ]:
from dbio import from_db

In [ ]:
df_sql2 = from_db("exchange_rage_data", "exchage_rate")
df_sql2

# 여기서부터 2.4 내용 - 필수적임!! 다 익히기

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("./data/Titanic_train.csv") #불러오기
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
print(df) # 결과 이상하게 나옴

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [4]:
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## 데이터 일부만 보기
- head(숫자), tail(숫자)
- 기본 값을 5개 행만 출력
- 60행까지 출력 가능

In [ ]:
df.head() # 처음 5개

In [ ]:
df.tail() # 끝 5개

In [ ]:
df.head(1)

# .info()
- 컬럼명, null이 아닌 데이터 개수, 데이터 타입을 동시에 출력

In [ ]:
df.info()

# .describe()
- 데이터 프레임의 **숫자 데이터**의 기초통계를 보여주는 함수
- count, mean, std, min, 25%, 50%, 75%, max
- .describe(include='all') : 문자형/카테고리형 데이터에서 유일값, 최빈값 출력

In [109]:
df.describe()
# 숫자 데이터만의 통계치 나옴

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [110]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

# 판다스 데이터 프레임에서 일부 자료만 추출하기

- 데이터 프레임에서 1개 컬럼만 가져오기

In [27]:
print(df['Name'], type(df['Name'])) # type=Series
print(df['Name'].shape) # (891,) -> 1차원임

# 1차원이어서 결과 안 예쁘게 나옴

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str <class 'pandas.Series'>
(891,)

In [ ]:
display(df[['Name']])
print(type(df[['Name']]), df[['Name']].ndim, df[['Name']].shape)

# 대괄호 하나 더 써주면 2차원으로 바뀌어서 데이터프레임 형태로 결과가 나옴
# 대괄호 2개 -> 2차원 
# -> type = DataFrame

- 2개 이상 컬럼을 가져오기

In [ ]:
df[['Age', 'Name']]

In [ ]:
df[['Age', 'Name','Cabin']]

# 컬럼명 출력하기 -> .columns

In [ ]:
df.columns
# 형태는 리스트지만 리스트 아님

In [ ]:
list(df.columns)
# 리스트로 바꿔줌

# 데이터 프레임에서 일부 컬럼만 가져오기2 - 중요!!
### 앞쪽은 행을 슬라이싱, 뒤쪽은 열을 슬라이싱한 것!
- loc : 인덱스 이름과 컬럼명으로 데이터의 일부를 추출해서 가져옴 -> **이름**으로 가져옴
```python
df.loc[시작row인덱스 이름 : 끝row인덱스 이름, ['컬럼명1', '컬럼명2']]
```
- iloc : 인덱스 번호를 이용해서 슬라이싱으로 데이터의 일부를 가져옴 -> **인덱스**로 가져옴
```python
df.iloc[시작row인덱스 번호 : 끝row인덱스 번호+1, 시작column인덱스 번호 : 끝column인덱스 번호+1]
```

- loc(이름)이 덜 헷갈려서 평소에는 loc 더 많이 씀!

In [28]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

- 이름과 나이 컬럼에서 인덱스 100-150번까지만 가져오고 싶을 때

In [29]:
df.loc[100:150, ['Name', 'Age']]

# 이름이 100, 150임 숫자들이 이름임!! 이름 100부터 이름150까지
# 앞쪽은 행을 슬라이싱, 뒤쪽은 열을 슬라이싱한 것!

                                                  Name   Age
100                            Petranec, Miss. Matilda  28.0
101                   Petroff, Mr. Pastcho ("Pentcho")   NaN
102                          White, Mr. Richard Frasar  21.0
103                         Johansson, Mr. Gustaf Joel  33.0
104                     Gustafsson, Mr. Anders Vilhelm  37.0
105                              Mionoff, Mr. Stoytcho  28.0
106                   Salkjelsvik, Miss. Anna Kristine  21.0
107                             Moss, Mr. Albert Johan   NaN
108                                    Rekic, Mr. Tido  38.0
109                                Moran, Miss. Bertha   NaN
110                     Porter, Mr. Walter Chamberlain  47.0
111                               Zabour, Miss. Hileni  14.5
112                             Barton, Mr. David John  22.0
113                            Jussila, Miss. Katriina  20.0
114                              Attalah, Miss. Malake  17.0
115                              Pekoniemi, Mr. Edvard  21.0
116                               Connors, Mr. Patrick  70.5
117                    Turpin, Mr. William John Robert  29.0
118                           Baxter, Mr. Quigg Edmond  24.0
119                  Andersson, Miss. Ellis Anna Maria   2.0
120                        Hickman, Mr. Stanley George  21.0
121                         Moore, Mr. Leonard Charles   NaN
122                               Nasser, Mr. Nicholas  32.5
123                                Webber, Miss. Susan  32.5
124                        White, Mr. Percival Wayland  54.0
125                       Nicola-Yarred, Master. Elias  12.0
126                                McMahon, Mr. Martin   NaN
127                          Madsen, Mr. Fridtjof Arne  24.0
128                                  Peter, Miss. Anna   NaN
129                                 Ekstrom, Mr. Johan  45.0
130                               Drazenoic, Mr. Jozef  33.0
131                     Coelho, Mr. Domingos Fernandeo  20.0
132     Robins, Mrs. Alexander A (Grace Charity Laury)  47.0
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  29.0
134                     Sobey, Mr. Samuel James Hayden  25.0
135                                 Richard, Mr. Emile  23.0
136                       Newsom, Miss. Helen Monypeny  19.0
137                        Futrelle, Mr. Jacques Heath  37.0
138                                Osen, Mr. Olaf Elon  16.0
139                                 Giglio, Mr. Victor  24.0
140                      Boulos, Mrs. Joseph (Sultana)   NaN
141                           Nysten, Miss. Anna Sofia  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  24.0
143                                Burke, Mr. Jeremiah  19.0
144                         Andrew, Mr. Edgardo Samuel  18.0
145                       Nicholls, Mr. Joseph Charles  19.0
146       Andersson, Mr. August Edvard ("Wennerstrom")  27.0
147                   Ford, Miss. Robina Maggie "Ruby"   9.0
148           Navratil, Mr. Michel ("Louis M Hoffman")  36.5
149                  Byles, Rev. Thomas Roussel Davids  42.0
150                         Bateman, Rev. Robert James  51.0

In [30]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
df.iloc[100:151, ::2]
# 인덱스 번호를 100-150번까지
# iloc -> 슬라이싱 가능(건너뛰기 가능!)

     PassengerId  Pclass     Sex  SibSp              Ticket    Cabin
100          101       3  female      0              349245      NaN
101          102       3    male      0              349215      NaN
102          103       1    male      0               35281      D26
103          104       3    male      0                7540      NaN
104          105       3    male      2             3101276      NaN
105          106       3    male      0              349207      NaN
106          107       3  female      0              343120      NaN
107          108       3    male      0              312991      NaN
108          109       3    male      0              349249      NaN
109          110       3  female      1              371110      NaN
110          111       1    male      0              110465     C110
111          112       3  female      1                2665      NaN
112          113       3    male      0              324669      NaN
113          114       3  female      1                4136      NaN
114          115       3  female      0                2627      NaN
115          116       3    male      0   STON/O 2. 3101294      NaN
116          117       3    male      0              370369      NaN
117          118       2    male      1               11668      NaN
118          119       1    male      0            PC 17558  B58 B60
119          120       3  female      4              347082      NaN
120          121       2    male      2        S.O.C. 14879      NaN
121          122       3    male      0           A4. 54510      NaN
122          123       2    male      1              237736      NaN
123          124       2  female      0               27267     E101
124          125       1    male      0               35281      D26
125          126       3    male      1                2651      NaN
126          127       3    male      0              370372      NaN
127          128       3    male      0             C 17369      NaN
128          129       3  female      1                2668    F E69
129          130       3    male      0              347061      NaN
130          131       3    male      0              349241      NaN
131          132       3    male      0  SOTON/O.Q. 3101307      NaN
132          133       3  female      1           A/5. 3337      NaN
133          134       2  female      1              228414      NaN
134          135       2    male      0          C.A. 29178      NaN
135          136       2    male      0       SC/PARIS 2133      NaN
136          137       1  female      0               11752      D47
137          138       1    male      1              113803     C123
138          139       3    male      0                7534      NaN
139          140       1    male      0            PC 17593      B86
140          141       3  female      0                2678      NaN
141          142       3  female      0              347081      NaN
142          143       3  female      1    STON/O2. 3101279      NaN
143          144       3    male      0              365222      NaN
144          145       2    male      0              231945      NaN
145          146       2    male      1          C.A. 33112      NaN
146          147       3    male      0              350043      NaN
147          148       3  female      2          W./C. 6608      NaN
148          149       2    male      0              230080       F2
149          150       2    male      0              244310      NaN
150          151       2    male      0         S.O.P. 1166      NaN

# 특정 컬럼에서 유일값, 유일값의 개수
- unique(): 유일값만 출력
- nunique(): 유일값의 개수만 출력

In [32]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [33]:
df['Pclass'].unique()

array([3, 1, 2])

In [72]:
df['Pclass'].nunique()

3

In [34]:
df['Embarked'].unique()

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [35]:
df['Embarked'].nunique()

3

# 카테고리 컬럼에서 유일값 별 개수를 세는 함수
- value_counts()

In [36]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

# 데이터를 정렬하는 함수
- sort_values(by="컬럼명")

In [41]:
df.sort_values(by="Pclass", ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
853,854,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C

- 정렬 기준을 2개 컬럼 이상으로 하고 싶을 때

In [42]:
df.sort_values(by=['Pclass','Age'], ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C

# 컬럼을 인덱스로 지정하기
- set_index("컬럼명")

In [45]:
df=df.set_index("PassengerId")
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

- 2개 이상의 컬럼을 인덱스로 지정 - 멀티 인덱스

In [32]:
df2=df.set_index(['PassengerId','Name'])
df2

,,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [52]:
df2.index
# 2개 이상의 컬럼을 인덱스로 지정 - 멀티인덱스

MultiIndex([(  1,                             'Braund, Mr. Owen Harris'),
            (  2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'),
            (  3,                              'Heikkinen, Miss. Laina'),
            (  4,        'Futrelle, Mrs. Jacques Heath (Lily May Peel)'),
            (  5,                            'Allen, Mr. William Henry'),
            (  6,                                    'Moran, Mr. James'),
            (  7,                             'McCarthy, Mr. Timothy J'),
            (  8,                      'Palsson, Master. Gosta Leonard'),
            (  9,   'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'),
            ( 10,                 'Nasser, Mrs. Nicholas (Adele Achem)'),
            ...
            (882,                                  'Markun, Mr. Johann'),
            (883,                        'Dahlberg, Miss. Gerda Ulrika'),
            (884,                       'Banfield, Mr. Frederick James'),
            (885,                              'Sutehall, Mr. Henry Jr'),
            (886,                'Rice, Mrs. William (Margaret Norton)'),
            (887,                               'Montvila, Rev. Juozas'),
            (888,                        'Graham, Miss. Margaret Edith'),
            (889,            'Johnston, Miss. Catherine Helen "Carrie"'),
            (890,                               'Behr, Mr. Karl Howell'),
            (891,                                 'Dooley, Mr. Patrick')],
           names=['PassengerId', 'Name'], length=891)

In [53]:
df2 # PassengerId, Name 인덱스 됨!

,,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [73]:
df2.loc[(1,'Braund, Mr. Owen Harris'), ['Pclass', 'Age']]

Pclass     3.0
Age       22.0
Name: (1, Braund, Mr. Owen Harris), dtype: float64

In [74]:
df2.loc[(1,'Braund, Mr. Owen Harris') : (5,'Allen, Mr. William Henry'), ['Pclass', 'Age']]

                                                                Pclass   Age
PassengerId Name
1           Braund, Mr. Owen Harris                                  3  22.0
2           Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  38.0
3           Heikkinen, Miss. Laina                                   3  26.0
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  35.0
5           Allen, Mr. William Henry                                 3  35.0

In [56]:
df2.iloc[0:5, [1,3]]

                                                                Pclass   Age
PassengerId Name
1           Braund, Mr. Owen Harris                                  3  22.0
2           Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  38.0
3           Heikkinen, Miss. Laina                                   3  26.0
4           Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  35.0
5           Allen, Mr. William Henry                                 3  35.0

# 인덱스를 컬럼으로 되돌리기
- reset_index(dorp=True)

In [75]:
df = df.reset_index()
df

,index,PassengerId,Survived,Pclass,성,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,가족수
0,0,1,0,3,Harris,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,1,2,1,1,Harris,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,2,3,1,3,Harris,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,1,Harris,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,4,5,0,3,Harris,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,Harris,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,887,888,1,1,Harris,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,888,889,0,3,Harris,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,889,890,1,1,Harris,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,890,891,0,3,Harris,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

# 컬럼/인덱스 이름 변경하기
- rename(columns={'원래이름':'새이름','원래이름2':'새이름2'})
- rename(index={'원래이름':'새이름','원래이름2':'새이름2'})

In [33]:
df2 = df2.rename(columns={'Pclass' : "선실등급", 'Sex' : "성별"})
df2

,,Survived,선실등급,성별,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [77]:
df2.index

MultiIndex([(  1,                             'Braund, Mr. Owen Harris'),
            (  2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'),
            (  3,                              'Heikkinen, Miss. Laina'),
            (  4,        'Futrelle, Mrs. Jacques Heath (Lily May Peel)'),
            (  5,                            'Allen, Mr. William Henry'),
            (  6,                                    'Moran, Mr. James'),
            (  7,                             'McCarthy, Mr. Timothy J'),
            (  8,                      'Palsson, Master. Gosta Leonard'),
            (  9,   'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'),
            ( 10,                 'Nasser, Mrs. Nicholas (Adele Achem)'),
            ...
            (882,                                  'Markun, Mr. Johann'),
            (883,                        'Dahlberg, Miss. Gerda Ulrika'),
            (884,                       'Banfield, Mr. Frederick James'),
            (885,                              'Sutehall, Mr. Henry Jr'),
            (886,                'Rice, Mrs. William (Margaret Norton)'),
            (887,                               'Montvila, Rev. Juozas'),
            (888,                        'Graham, Miss. Margaret Edith'),
            (889,            'Johnston, Miss. Catherine Helen "Carrie"'),
            (890,                               'Behr, Mr. Karl Howell'),
            (891,                                 'Dooley, Mr. Patrick')],
           names=['PassengerId', 'Name'], length=891)

In [78]:
df

,index,PassengerId,Survived,Pclass,성,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,가족수
0,0,1,0,3,Harris,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,1,2,1,1,Harris,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,2,3,1,3,Harris,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,1,Harris,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,4,5,0,3,Harris,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,Harris,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,887,888,1,1,Harris,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,888,889,0,3,Harris,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,889,890,1,1,Harris,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,890,891,0,3,Harris,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [79]:
df.rename(index={0 : '영', 1 : "일"})

,index,PassengerId,Survived,Pclass,성,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,가족수
영,0,1,0,3,Harris,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
일,1,2,1,1,Harris,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,2,3,1,3,Harris,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,1,Harris,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,4,5,0,3,Harris,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,Harris,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,887,888,1,1,Harris,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,888,889,0,3,Harris,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,889,890,1,1,Harris,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,890,891,0,3,Harris,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

- .colums를 이용한 컬럼명 수정
- 컬럼의 개수와 변경할 컬럼 이름의 개수가 동일해야지만 작동

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [6]:
newcols = ['승객번호', '생존여부', '선실등급', '이름', '성별', '나이', '형제자매수',
          '부모자녀수', '티켓번호', '티켓가격', '선실번호', '승선지']

In [7]:
print("df.columns", len(df.columns), "newcols", len(newcols))

df.columns 12 newcols 12

In [8]:
df.columns = newcols
df

,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,선실번호,승선지
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [104]:
df

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,가족수
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

# 인덱스를 컬럼으로 되돌리기
- reset_index(drop=True)

In [115]:
df=df.reset_index() # 기본값은 drop=False
df

,index,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,선실번호,승선지
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [116]:
df.reset_index(drop=True)

,index,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,선실번호,승선지
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# 컬럼 추가하기
- dict의 key, value 추가하는 것과 동일
- 변수명[key]=value
- 데이터프레임변수명['컬럼명']=value

In [117]:
df['가족수']=0
df

,index,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,선실번호,승선지,가족수
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

# 원하는 위치에 컬럼 추가하기
- 변수명.insert(위치인덱스, '컬럼명', value)

In [118]:
df.insert(3, "성", "Harris")

In [119]:
df.columns

Index(['index', '승객번호', '생존여부', '성', '선실등급', '이름', '성별', '나이', '형제자매수',
       '부모자녀수', '티켓번호', '티켓가격', '선실번호', '승선지', '가족수'],
      dtype='str')

In [120]:
df['가족수'] = df['형제자매수'] + df['부모자녀수']
df

,index,승객번호,생존여부,성,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,선실번호,승선지,가족수
0,0,1,0,Harris,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,1,2,1,Harris,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,2,3,1,Harris,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,Harris,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,4,5,0,Harris,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,Harris,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,887,888,1,Harris,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,888,889,0,Harris,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,889,890,1,Harris,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,890,891,0,Harris,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

# 컬럼 삭제하기
- del 변수명['컬럼명']
- df.drop('컬럼명', axis=1)
- df.drop(['컬럼명1''컬럼명2'], axis=1)

-> 보통 drop을 많이 씀

In [121]:
del df['성']
df

,index,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,선실번호,승선지,가족수
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,0

In [101]:
df.columns

Index(['index', 'PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age',
       'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', '가족수'],
      dtype='str')

In [122]:
df = df.drop(['형제자매수', '부모자녀수'], axis=1)
df

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,3
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,0

In [103]:
df2

,,Survived,선실등급,성별,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

# 데이터 타입 바꾸기
- .astype(자료형)
- .apply(형변환함수)

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   성            891 non-null    str
 4   Name         891 non-null    str
 5   Sex          891 non-null    str
 6   Age          714 non-null    float64
 7   SibSp        891 non-null    int64
 8   Parch        891 non-null    int64
 9   Ticket       891 non-null    str
 10  Fare         891 non-null    float64
 11  Cabin        204 non-null    str
 12  Embarked     889 non-null    str
 13  가족수          891 non-null    int64
dtypes: float64(2), int64(6), str(6)
memory usage: 97.6 KB

In [123]:
df['티켓가격'].astype('int')

0       7
1      71
2       7
3      53
4       8
       ..
886    13
887    30
888    23
889    30
890     7
Name: 티켓가격, Length: 891, dtype: int64

In [124]:
df['승객번호'].astype('str')

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: 승객번호, Length: 891, dtype: str

In [125]:
df['승객번호'].apply(str)

0        1
1        2
2        3
3        4
4        5
      ...
886    887
887    888
888    889
889    890
890    891
Name: 승객번호, Length: 891, dtype: str

# apply 함수
- 컬럼의 자료나 데이터프레임의 행을 하나씩 꺼내서 함수 처리 후 재할당
- series.apply() : 자료를 순차적으로 꺼내서 apply 안쪽의 함수 처리
- DataFrame.apply(함수, axis=1) : 데이터 프레임의 행을 1개씩 꺼내서 함수 처리

In [126]:
# df['승객번호']의 요소를 꺼내서 홀수, 짝수로 출력하기
df['승객번호'].apply(lambda x:"짝수" if x%2==0 else '홀수')

0      홀수
1      짝수
2      홀수
3      짝수
4      홀수
       ..
886    홀수
887    짝수
888    홀수
889    짝수
890    홀수
Name: 승객번호, Length: 891, dtype: str

In [34]:
df['승객번호'].apply(lambda x: np.where(x % 2 == 0, "짝수", "홀수"))

KeyError: '승객번호'

In [129]:
df.apply(lambda x:x[['이름','성별']], axis=1)
# 한 행씩 가져와서 처리

                                                    이름      성별
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

# 판다스 데이터 프레임에서 조건에 맞는 행만 가져오기
- 원하는 것만 가져옴
```python
df['컬럼명'] 조건식
```
- 조건식 연산자 >,<,>=,<=,==, !=, &, |

In [131]:
# 승객번호가 3번인 행을 출력하세요
df[df['승객번호']==3]
# df['승객번호']==3 조건이 True인 것만 또 대괄호로 인덱스 함!

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.925,NaN,S,0

In [132]:
# 나이가 35 초과인 사람만 필터링
df[df['나이']>35]

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
6,6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,17463,51.8625,E46,S,0
11,11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,113783,26.5500,C103,S,0
13,13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,347082,31.2750,NaN,S,6
15,15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,248706,16.0000,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
865,865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,236852,13.0000,NaN,S,0
871,871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,11751,52.5542,D35,S,2
873,873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,345765,9.0000,NaN,S,0
879,879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,11767,83.1583,C50,C,1
885,885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,382652,29.1250,NaN,Q,5

- 조건이 2개 이상인 경우 and 조건 : &
df[(df[컬럼명1]==조건1) & (df[컬럼명2] == 조건2)]

In [130]:
# 성별이 여성이면서 나이가 35세 초과인 행찾기 & 조건
df[(df['성별'] == "female") & (df['나이'] > 35)]

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1
11,11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,113783,26.5500,C103,S,0
15,15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,248706,16.0000,NaN,S,0
25,25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,347077,31.3875,NaN,S,6
40,40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,7546,9.4750,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
862,862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,17466,25.9292,D17,S,0
865,865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,236852,13.0000,NaN,S,0
871,871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,11751,52.5542,D35,S,2
879,879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,11767,83.1583,C50,C,1
885,885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,382652,29.1250,NaN,Q,5

In [133]:
# 성별이 남성, 선실등급 1, 생존여부가 1인 사람들을 찾으세요
df[(df['성별'] == 'male') & (df['선실등급'] == 1) & (df['생존여부'] ==1)]

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
23,23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,113788,35.5000,A6,S,0
55,55,56,1,1,"Woolner, Mr. Hugh",male,NaN,19947,35.5000,C52,S,0
97,97,98,1,1,"Greenfield, Mr. William Bertram",male,23.00,PC 17759,63.3583,D10 D12,C,1
187,187,188,1,1,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.00,111428,26.5500,NaN,S,0
209,209,210,1,1,"Blank, Mr. Henry",male,40.00,112277,31.0000,A31,C,0
224,224,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.00,19943,90.0000,C93,S,1
248,248,249,1,1,"Beckwith, Mr. Richard Leonard",male,37.00,11751,52.5542,D35,S,2
298,298,299,1,1,"Saalfeld, Mr. Adolphe",male,NaN,19988,30.5000,C106,S,0
305,305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,113781,151.5500,C22 C26,S,3
370,370,371,1,1,"Harder, Mr. George Achilles",male,25.00,11765,55.4417,E50,C,1
390,390,391,1,1,"Carter, Mr. William Ernest",male,36.00,113760,120.0000,B96 B98,S,3
430,430,431,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.00,110564,26.5500,C52,S,0
445,445,446,1,1,"Dodge, Master. Washington",male,4.00,33638,81.8583,A34,S,2
447,447,448,1,1,"Seward, Mr. Frederic Kimber",male,34.00,113794,26.5500,NaN,S,0
449,449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.00,113786,30.5000,C104,S,0
453,453,454,1,1,"Goldenberg, Mr. Samuel L",male,49.00,17453,89.1042,C92,C,1
460,460,461,1,1,"Anderson, Mr. Harry",male,48.00,19952,26.5500,E12,S,0
484,484,485,1,1,"Bishop, Mr. Dickinson H",male,25.00,11967,91.0792,B49,C,1
507,507,508,1,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,111427,26.5500,NaN,S,0
512,512,513,1,1,"McGough, Mr. James Robert",male,36.00,PC 17473,26.2875,E25,S,0
550,550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,17421,110.8833,C70,C,2
572,572,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.00,PC 17474,26.3875,E25,S,0
587,587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.00,13567,79.2000,B41,C,2
599,599,600,1,1,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",male,49.00,PC 17485,56.9292,A20,C,1
604,604,605,1,1,"Homer, Mr. Harry (""Mr E Haven"")",male,35.00,111426,26.5500,NaN,C,0
607,607,608,1,1,"Daniel, Mr. Robert Williams",male,27.00,113804,30.5000,NaN,S,0
621,621,622,1,1,"Kimball, Mr. Edwin Nelson Jr",male,42.00,11753,52.5542,D19,S,1
630,630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,27042,30.0000,A23,S,0
632,632,633,1,1,"Stahelin-Maeglin, Dr. Max",male,32.00,13214,30.5000,B50,C,0
645,645,646,1,1,"Harper, Mr. Henry Sleeper",male,48.00,PC 17572,76.7292,D33,C,1
647,647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.00,13213,35.5000,A26,C,0
660,660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,PC 17611,133.6500,NaN,S,2
679,679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,PC 17755,512.3292,B51 B53 B55,C,1
681,681,682,1,1,"Hassab, Mr. Hammad",male,27.00,PC 17572,76.7292,D49,C,0
690,690,691,1,1,"Dick, Mr. Albert Adrian",male,31.00,17474,57.0000,B20,S,1
701,701,702,1,1,"Silverthorne, Mr. Spencer Victor",male,35.00,PC 17475,26.2875,E24,S,0
707,707,708,1,1,"Calderhead, Mr. Edward Pennington",male,42.00,PC 17476,26.2875,E24,S,0
712,712,713,1,1,"Taylor, Mr. Elmer Zebley",male,48.00,19996,52.0000,C126,S,1
724,724,725,1,1,"Chambers, Mr. Norman Campbell",male,27.00,113806,53.1000,E8,S,1
737,737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,PC 17755,512.3292,B101,C,0
740,740,741,1,1,"Hawksford, Mr. Walter James",male,NaN,16988,30.0000,D45,S,0
802,802,803,1,1,"Carter, Master. William Thornton II",male,11.00,113760,120.0000,B96 B98,S,3
839,839,840,1,1,"Marechal, Mr. Pierre",male,NaN,11774,29.7000,C47,C,0
857,857,858,1,1,"Daly, Mr. Peter Denis",male,51.00,113055,26.5500,E17,S,0
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,111369,30.0000,C148,C,0

In [134]:
# 성별이 남성, 선실등급 1 혹은 2이고, 생존여부가 1인 사람들을 찾으세요
df[(df['성별'] == 'male') & ((df['선실등급'] == 1) | (df['선실등급'] == 2)) & (df['생존여부'] == 1)]

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
17,17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,244373,13.0000,NaN,S,0
21,21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,248698,13.0000,D56,S,0
23,23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,113788,35.5000,A6,S,0
55,55,56,1,1,"Woolner, Mr. Hugh",male,NaN,19947,35.5000,C52,S,0
78,78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,248738,29.0000,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...
827,827,828,1,2,"Mallet, Master. Andre",male,1.00,S.C./PARIS 2079,37.0042,NaN,C,2
831,831,832,1,2,"Richards, Master. George Sibley",male,0.83,29106,18.7500,NaN,S,2
839,839,840,1,1,"Marechal, Mr. Pierre",male,NaN,11774,29.7000,C47,C,0
857,857,858,1,1,"Daly, Mr. Peter Denis",male,51.00,113055,26.5500,E17,S,0
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,111369,30.0000,C148,C,0

In [135]:
# or = .isin 으로 처리 가능!
df[(df['성별'] == 'male') & (df['선실등급'].isin([1,2])) & (df['생존여부'] == 1)]

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
17,17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,244373,13.0000,NaN,S,0
21,21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,248698,13.0000,D56,S,0
23,23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,113788,35.5000,A6,S,0
55,55,56,1,1,"Woolner, Mr. Hugh",male,NaN,19947,35.5000,C52,S,0
78,78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,248738,29.0000,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...,...
827,827,828,1,2,"Mallet, Master. Andre",male,1.00,S.C./PARIS 2079,37.0042,NaN,C,2
831,831,832,1,2,"Richards, Master. George Sibley",male,0.83,29106,18.7500,NaN,S,2
839,839,840,1,1,"Marechal, Mr. Pierre",male,NaN,11774,29.7000,C47,C,0
857,857,858,1,1,"Daly, Mr. Peter Denis",male,51.00,113055,26.5500,E17,S,0
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,111369,30.0000,C148,C,0

- 선실 등급 별 승차권 금액의 최소, 최대, 평균 등 4분위수를 보고 싶을 떄 1등실만 필터링

In [136]:
# 1등급실인 사람들의 티켓 가격(의 최소, 최대, 평균 등 4분위수)만 출력
df[df['선실등급'] == 1]['티켓가격'].describe()

count    216.000000
mean      84.154687
std       78.380373
min        0.000000
25%       30.923950
50%       60.287500
75%       93.500000
max      512.329200
Name: 티켓가격, dtype: float64

In [137]:
# 2등급실
df[df['선실등급'] == 2]['티켓가격'].describe()

count    184.000000
mean      20.662183
std       13.417399
min        0.000000
25%       13.000000
50%       14.250000
75%       26.000000
max       73.500000
Name: 티켓가격, dtype: float64

# 조건에 맞는 행을 찾은 후 특정 컬럼만 조회하기

In [138]:
# 선실 등급이 1이거나 2면서 생존한 여성들 중에서 나이만보고 싶을 때

df[(df['선실등급'].isin([1,2])) & (df['생존여부'] == 1) & (df['성별'] == 'female')]['나이']

1      38.0
3      35.0
9      14.0
11     58.0
15     55.0
       ...
871    47.0
874    28.0
879    56.0
880    25.0
887    19.0
Name: 나이, Length: 161, dtype: float64

In [139]:
# loc 써서 컬럼 조회 - 정석적인 방법임
# 선실등급이 1 이거나 2면서 생존한 여성들 중에서 나이만 보고 싶을 때

df.loc[(df['선실등급'].isin([1,2])) & (df['생존여부'] == 1) & (df['성별'] == 'female'), '나이']

1      38.0
3      35.0
9      14.0
11     58.0
15     55.0
       ...
871    47.0
874    28.0
879    56.0
880    25.0
887    19.0
Name: 나이, Length: 161, dtype: float64

In [140]:
# 선실등급이 1 이거나 2면서 생존한 여성들 중에서 나이와 이름을 보고 싶을 때
# 나이, 이름-> 리스트로 넣어서 조회하기

df.loc[(df['선실등급'].isin([1,2])) & (df['생존여부'] == 1) & (df['성별'] == 'female'), ['나이','이름']]

       나이                                                 이름
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
9    14.0                Nasser, Mrs. Nicholas (Adele Achem)
11   58.0                           Bonnell, Miss. Elizabeth
15   55.0                   Hewlett, Mrs. (Mary D Kingcome)
..    ...                                                ...
871  47.0   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
874  28.0              Abelson, Mrs. Samuel (Hannah Wizosky)
879  56.0      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880  25.0       Shelley, Mrs. William (Imanita Parrish Hall)
887  19.0                       Graham, Miss. Margaret Edith

[161 rows x 2 columns]

# Series와 함께 사용하는 문자열 함수
### .str. 쓰면 반복문 안 해도 전체 요소에 적용됨
- .str.contains()
- .str.split()
- .str.replace()
- .str.lower()
- .str.upper()
- .str.join()
- .str.strip()

- 특정 단어를 포함한 행 찾기
- .str.contains("찾을 단어")
- SQL에서는 : where 이름 like '%joseph%'

In [142]:
df[df['이름']=='Joseph']

# 결과 안 나옴 -> 'Joseph' 으로 정확히 일치해야 함

Empty DataFrame
Columns: [index, 승객번호, 생존여부, 선실등급, 이름, 성별, 나이, 티켓번호, 티켓가격, 선실번호, 승선지, 가족수]
Index: []

In [143]:
df[df['이름'].str.contains('Joseph')]

# 'Joseph'이 포함되면 모두 출력

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수
20,20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,239865,26.0000,NaN,S,0
34,34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,PC 17604,82.1708,NaN,C,1
95,95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,374910,8.0500,NaN,S,0
140,140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,2678,15.2458,NaN,C,2
145,145,146,0,2,"Nicholls, Mr. Joseph Charles",male,19.0,C.A. 33112,36.7500,NaN,S,2
194,194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,PC 17610,27.7208,B4,C,0
375,375,376,1,1,"Meyer, Mrs. Edgar Joseph (Leila Saks)",female,NaN,PC 17604,82.1708,NaN,C,1
454,454,455,0,3,"Peduzzi, Mr. Joseph",male,NaN,A/5 2817,8.0500,NaN,S,0
532,532,533,0,3,"Elias, Mr. Joseph Jr",male,17.0,2690,7.2292,NaN,C,2
559,559,560,1,3,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",female,36.0,345572,17.4000,NaN,S,1
578,578,579,0,3,"Caram, Mrs. Joseph (Maria Elias)",female,NaN,2689,14.4583,NaN,C,1
589,589,590,0,3,"Murdlin, Mr. Joseph",male,NaN,A./5. 3235,8.0500,NaN,S,0
608,608,609,1,2,"Laroche, Mrs. Joseph (Juliette Marie Louise La...",female,22.0,SC/Paris 2123,41.5792,NaN,C,3
685,685,686,0,2,"Laroche, Mr. Joseph Philippe Lemercier",male,25.0,SC/Paris 2123,41.5792,NaN,C,3
752,752,753,0,3,"Vande Velde, Mr. Johannes Joseph",male,33.0,345780,9.5000,NaN,S,0
828,828,829,1,3,"McCormack, Mr. Thomas Joseph",male,NaN,367228,7.7500,NaN,Q,0

In [9]:
df['이름'].split(",") # 문자열(str)에서만 split 가능
# df['이름'] 은 series여서 split 불가능

AttributeError: 'Series' object has no attribute 'split'

In [145]:
df['이름'][0].split(",")

['Braund', ' Mr. Owen Harris']

In [146]:
df['이름'].str.split(",") # df['이름'] split 가능

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: 이름, Length: 891, dtype: object

In [147]:
df['이름'].str.split(",", expand=True)

             0                                            1
0       Braund                              Mr. Owen Harris
1      Cumings   Mrs. John Bradley (Florence Briggs Thayer)
2    Heikkinen                                  Miss. Laina
3     Futrelle           Mrs. Jacques Heath (Lily May Peel)
4        Allen                            Mr. William Henry
..         ...                                          ...
886   Montvila                                  Rev. Juozas
887     Graham                         Miss. Margaret Edith
888   Johnston               Miss. Catherine Helen "Carrie"
889       Behr                              Mr. Karl Howell
890     Dooley                                  Mr. Patrick

[891 rows x 2 columns]

In [148]:
# 컬럼 2개로 나눠서 넣기
df[["First_name","Last_name"]]= df['이름'].str.split(",", expand=True)
df

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수,First_name,Last_name
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1,Braund,Mr. Owen Harris
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0,Heikkinen,Miss. Laina
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0,Allen,Mr. William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0,Montvila,Rev. Juozas
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0,Graham,Miss. Margaret Edith
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,3,Johnston,"Miss. Catherine Helen ""Carrie"""
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0,Behr,Mr. Karl Howell
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,0,Dooley,Mr. Patrick

In [151]:
# 괄호() 없애기

# .str.replace("없앨문자", "새문자")
df['이름'].str.replace("(","").str.replace(")","")

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley Florence Briggs Thayer
2                                 Heikkinen, Miss. Laina
3             Futrelle, Mrs. Jacques Heath Lily May Peel
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: 이름, Length: 891, dtype: str

In [160]:
# lower
df['이름'].str.lower
df

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수,First_name,Last_name,name_list
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1,Braund,Mr. Owen Harris,"[Braund,, Mr., Owen, Harris]"
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1,Cumings,Mrs. John Bradley (Florence Briggs Thayer),"[Cumings,, Mrs., John, Bradley, (Florence, Bri..."
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0,Heikkinen,Miss. Laina,"[Heikkinen,, Miss., Laina]"
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1,Futrelle,Mrs. Jacques Heath (Lily May Peel),"[Futrelle,, Mrs., Jacques, Heath, (Lily, May, ..."
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0,Allen,Mr. William Henry,"[Allen,, Mr., William, Henry]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0,Montvila,Rev. Juozas,"[Montvila,, Rev., Juozas]"
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0,Graham,Miss. Margaret Edith,"[Graham,, Miss., Margaret, Edith]"
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,3,Johnston,"Miss. Catherine Helen ""Carrie""","[Johnston,, Miss., Catherine, Helen, ""Carrie""]"
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0,Behr,Mr. Karl Howell,"[Behr,, Mr., Karl, Howell]"
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,0,Dooley,Mr. Patrick,"[Dooley,, Mr., Patrick]"

In [161]:
# upper
df['이름'].str.upper
df

,index,승객번호,생존여부,선실등급,이름,성별,나이,티켓번호,티켓가격,선실번호,승선지,가족수,First_name,Last_name,name_list
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,1,Braund,Mr. Owen Harris,"[Braund,, Mr., Owen, Harris]"
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,1,Cumings,Mrs. John Bradley (Florence Briggs Thayer),"[Cumings,, Mrs., John, Bradley, (Florence, Bri..."
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,0,Heikkinen,Miss. Laina,"[Heikkinen,, Miss., Laina]"
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,1,Futrelle,Mrs. Jacques Heath (Lily May Peel),"[Futrelle,, Mrs., Jacques, Heath, (Lily, May, ..."
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,0,Allen,Mr. William Henry,"[Allen,, Mr., William, Henry]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,0,Montvila,Rev. Juozas,"[Montvila,, Rev., Juozas]"
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,0,Graham,Miss. Margaret Edith,"[Graham,, Miss., Margaret, Edith]"
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,3,Johnston,"Miss. Catherine Helen ""Carrie""","[Johnston,, Miss., Catherine, Helen, ""Carrie""]"
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,0,Behr,Mr. Karl Howell,"[Behr,, Mr., Karl, Howell]"
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,0,Dooley,Mr. Patrick,"[Dooley,, Mr., Patrick]"

In [162]:
df['name_list']=df['이름'].str.split()

In [ ]:
# .str.join("구분자") 
# 파이썬 문자열 함수에서는 -> " ".join(list)

In [164]:
df['name_list'].str.join(' ')
# 구분자로 합쳐짐

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: name_list, Length: 891, dtype: object

In [157]:
# 공백 없이 정리됨
df['이름'].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: 이름, Length: 891, dtype: str

# groupby
- 측정 기준 컬럼을 지정해서 다른 컬럼의 통계량 (평균, 최소, 최대, 개수)
```python
df.groupby('기준컬럼')[['보고싶은 컬럼'].집합함수(sum(), mean(), max())
df[['보고싶은 컬럼1', '보고싶은 컬럼2']].groupby('기준컬럼').집합함수
                   ```

In [10]:
df.columns

Index(['승객번호', '생존여부', '선실등급', '이름', '성별', '나이', '형제자매수', '부모자녀수', '티켓번호',
       '티켓가격', '선실번호', '승선지'],
      dtype='str')

- 성별 별 생존자 수

In [11]:
df.groupby('성별')['생존여부'].value_counts()

성별      생존여부
female  1       233
        0        81
male    0       468
        1       109
Name: count, dtype: int64

In [12]:
surv=df[['성별','생존여부']].groupby('성별').value_counts()

In [13]:
surv_df=pd.DataFrame(surv)
surv_df

             count
성별     생존여부
female 1       233
       0        81
male   0       468
       1       109

In [14]:
surv_df.index

MultiIndex([('female', 1),
            ('female', 0),
            (  'male', 0),
            (  'male', 1)],
           names=['성별', '생존여부'])

In [ ]:
# 성별 별 생존율 구하기
# 여성 생존율 = 233/(233+81) *100
# 남성 생존율 = 109/(109+468) *100

In [15]:
surv_df.shape

(4, 1)

In [16]:
surv_df.index

MultiIndex([('female', 1),
            ('female', 0),
            (  'male', 0),
            (  'male', 1)],
           names=['성별', '생존여부'])

In [17]:
# 여성 생존율
female_surv=surv_df.loc[('female',1), 'count'] / (surv_df.loc[('female',1), 'count']+surv_df.loc[('female',0), 'count']) *100
female_surv

np.float64(74.20382165605095)

In [19]:
female_surv = surv_df.loc[('female', 1), 'count'] / (surv_df.loc[('female', 1), 'count'] + surv_df.loc[('female', 0), 'count']) * 100
male_surv = surv_df.loc[('male', 1), 'count'] / (surv_df.loc[('male', 1), 'count'] + surv_df.loc[('female', 0), 'count']) * 100
print("여성 생존율: ", female_surv)
print("남성 생존율: ", male_surv)

여성 생존율:  74.20382165605095
남성 생존율:  57.36842105263158

In [20]:
ticket_desc=df['티켓가격'].describe() # 사분위수 출력
ticket_desc

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: 티켓가격, dtype: float64

In [21]:
ticket_desc.index

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='str')

In [22]:
ticket_desc['25%']

np.float64(7.9104)

- groupby 조건을 2개 이상 줄 때

In [23]:
df.columns

Index(['승객번호', '생존여부', '선실등급', '이름', '성별', '나이', '형제자매수', '부모자녀수', '티켓번호',
       '티켓가격', '선실번호', '승선지'],
      dtype='str')

In [24]:
# 성별 별, 선실등급 별 생존자 수
# 여러 개니까 괄호 2개 [[]]
df[['성별','선실등급','생존여부']].groupby(['성별','선실등급']).value_counts()

성별      선실등급  생존여부
female  1     1        91
              0         3
        2     1        70
              0         6
        3     1        72
              0        72
male    1     0        77
              1        45
        2     0        91
              1        17
        3     0       300
              1        47
Name: count, dtype: int64

In [25]:
# 성별 별, 선실등급 별 생존률(확률)
# 여러 개니까 괄호 2개 [[]]
df[['성별','선실등급','생존여부']].groupby(['성별','선실등급']).mean()*100

                  생존여부
성별     선실등급
female 1     96.808511
       2     92.105263
       3     50.000000
male   1     36.885246
       2     15.740741
       3     13.544669

- 그룹 연산 후 여러 개 함수 결과값 보기

In [26]:
# 성별 별 나이의 개수, 평균 나이, 최솟값, 최댓값
df[['성별','나이']].groupby('성별').describe()

           나이
        count       mean        std   min   25%   50%   75%   max
성별
female  261.0  27.915709  14.110146  0.75  18.0  27.0  37.0  63.0
male    453.0  30.726645  14.678201  0.42  21.0  29.0  39.0  80.0

- .agg([min,max])

In [27]:
df[['성별','나이']].groupby('성별').agg(['mean','min','max'])

               나이
             mean   min   max
성별
female  27.915709  0.75  63.0
male    30.726645  0.42  80.0

# 피벗테이블 pivot

In [28]:
df.pivot_table(values="생존여부", index="성별", columns='선실등급')

선실등급           1         2         3
성별
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

#  결측값 찾기 (값이 없는 것)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    int64
 1   생존여부    891 non-null    int64
 2   선실등급    891 non-null    int64
 3   이름      891 non-null    str
 4   성별      891 non-null    str
 5   나이      714 non-null    float64
 6   형제자매수   891 non-null    int64
 7   부모자녀수   891 non-null    int64
 8   티켓번호    891 non-null    str
 9   티켓가격    891 non-null    float64
 10  선실번호    204 non-null    str
 11  승선지     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

- isna() : 결측값인지 아닌지 확인 -> True(1), False(0) -> sum() : 덧셈=결측값의 개수

In [30]:
df.isna().sum()

승객번호       0
생존여부       0
선실등급       0
이름         0
성별         0
나이       177
형제자매수      0
부모자녀수      0
티켓번호       0
티켓가격       0
선실번호     687
승선지        2
dtype: int64

In [31]:
df.isna().sum() / len(df) * 100

승객번호      0.000000
생존여부      0.000000
선실등급      0.000000
이름        0.000000
성별        0.000000
나이       19.865320
형제자매수     0.000000
부모자녀수     0.000000
티켓번호      0.000000
티켓가격      0.000000
선실번호     77.104377
승선지       0.224467
dtype: float64

- dropna() : 결측값이 있는 행을 삭제

In [32]:
df.dropna()

,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,선실번호,승선지
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [33]:
df.drop('선실번호', axis=1).dropna()

,승객번호,생존여부,선실등급,이름,성별,나이,형제자매수,부모자녀수,티켓번호,티켓가격,승선지
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

- fillna() : 결측값을 다른 값으로 채워주는 함수

In [34]:
round(df['나이'].mean())

30

In [35]:
df = df.fillna(round(df['나이'].mean()))

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    int64
 1   생존여부    891 non-null    int64
 2   선실등급    891 non-null    int64
 3   이름      891 non-null    str
 4   성별      891 non-null    str
 5   나이      891 non-null    float64
 6   형제자매수   891 non-null    int64
 7   부모자녀수   891 non-null    int64
 8   티켓번호    891 non-null    str
 9   티켓가격    891 non-null    float64
 10  선실번호    891 non-null    object
 11  승선지     891 non-null    object
dtypes: float64(2), int64(5), object(2), str(3)
memory usage: 83.7+ KB

# 데이터프레임에서 결측값이 있는 행만 필터링

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    891 non-null    int64
 1   생존여부    891 non-null    int64
 2   선실등급    891 non-null    int64
 3   이름      891 non-null    str
 4   성별      891 non-null    str
 5   나이      891 non-null    float64
 6   형제자매수   891 non-null    int64
 7   부모자녀수   891 non-null    int64
 8   티켓번호    891 non-null    str
 9   티켓가격    891 non-null    float64
 10  선실번호    891 non-null    object
 11  승선지     891 non-null    object
dtypes: float64(2), int64(5), object(2), str(3)
memory usage: 83.7+ KB

In [38]:
df[df['승선지'].isna()==True]

Empty DataFrame
Columns: [승객번호, 생존여부, 선실등급, 이름, 성별, 나이, 형제자매수, 부모자녀수, 티켓번호, 티켓가격, 선실번호, 승선지]
Index: []

In [39]:
df2.info()

NameError: name 'df2' is not defined

In [200]:
df2[df2['Embarked'].isna()]
#'Embarked'가 NaN(결측값) 인 것들 필터링

,,Survived,선실등급,성별,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
62,"Icard, Miss. Amelie",1,1,female,38.0,0,0,113572,80.0,B28,NaN
830,"Stone, Mrs. George Nelson (Martha Evelyn)",1,1,female,62.0,0,0,113572,80.0,B28,NaN

In [201]:
df2[df2['Embarked'].isna()].index

MultiIndex([( 62,                       'Icard, Miss. Amelie'),
            (830, 'Stone, Mrs. George Nelson (Martha Evelyn)')],
           names=['PassengerId', 'Name'])

In [ ]:
df2['Age']=df2['Age'].fillna(round(df2['Age'].mean(), 1))

# 평균값으로 대치됨

In [ ]:
df2.loc[nan_index, :]

# 여러 개의 데이터 프레임 합치기
- concat : 2개의 데이터프레임을 1개로 합침
- merge : sql의 join과 같은 역할, 공통된 기준 컬럼을 매칭해서 합침
- join : sql의 join과 같은 역할, index가 같은 것끼리 합침

In [4]:
import os
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()
from dotenv import load_dotenv
load_dotenv()

True

In [5]:
dbid=os.getenv("dbid2")
dbpw=os.getenv("dbpw2")
host=os.getenv("host2")
port=os.getenv("port2")
dbname=os.getenv("dbname")

In [6]:
engine = create_engine(f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}/{dbname}")
conn = engine.connect()

In [7]:
passenger = pd.read_sql('p_info', con=conn)
ticket = pd.read_sql('t_info', con=conn)
survived = pd.read_sql("survived", con=conn)
passenger2 = pd.read_sql('passenger', con=conn)
ticket2 = pd.read_sql('ticket', con=conn)
survived2 = pd.read_sql("surv", con=conn)
conn.close()

In [8]:
passenger

,PassengerId,Name,Sex,Age,SibSp,Parch
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0

In [9]:
ticket

     PassengerId            Ticket  Pclass     Fare Cabin Embarked
0              1         A/5 21171       3   7.2500   NaN        S
1              2          PC 17599       1  71.2833   C85        C
2              3  STON/O2. 3101282       3   7.9250   NaN        S
3              4            113803       1  53.1000  C123        S
4              5            373450       3   8.0500   NaN        S
..           ...               ...     ...      ...   ...      ...
886          887            211536       2  13.0000   NaN        S
887          888            112053       1  30.0000   B42        S
888          889        W./C. 6607       3  23.4500   NaN        S
889          890            111369       1  30.0000  C148        C
890          891            370376       3   7.7500   NaN        Q

[891 rows x 6 columns]

In [10]:
survived

     PassengerId  Survived
0              1         0
1              2         1
2              3         1
3              4         1
4              5         0
..           ...       ...
886          887         0
887          888         1
888          889         0
889          890         1
890          891         0

[891 rows x 2 columns]

# concat
- 기준컬럼 없이 무조건 합침
- 기본값은 axis=0, 행방향으로 합침
- 옆으로 붙이고 싶으면 asix=1
- outer join이 기본값 - 무조건 다 합침

In [11]:
print("passenger", passenger.shape)
print("ticket", ticket.shape)
print("survived", survived.shape)

passenger (891, 6)
ticket (891, 6)
survived (891, 2)

In [12]:
pd.concat([passenger, ticket])

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
2,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
4,5,"Allen, Mr. William Henry",male,35.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
886,887,NaN,NaN,NaN,NaN,NaN,211536,2.0,13.00,NaN,S
887,888,NaN,NaN,NaN,NaN,NaN,112053,1.0,30.00,B42,S
888,889,NaN,NaN,NaN,NaN,NaN,W./C. 6607,3.0,23.45,NaN,S
889,890,NaN,NaN,NaN,NaN,NaN,111369,1.0,30.00,C148,C
890,891,NaN,NaN,NaN,NaN,NaN,370376,3.0,7.75,NaN,Q

In [13]:
pd.concat([passenger, ticket], axis=1)

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,887,211536,2,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,888,112053,1,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,889,W./C. 6607,3,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,890,111369,1,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,891,370376,3,7.7500,NaN,Q

# 인덱스가 섞여있는 데이터 프레임 합치기

In [14]:
print("passenger2", passenger2.shape)
print("ticket2", ticket2.shape)
print("survived2", survived2.shape)

passenger2 (623, 6)
ticket2 (445, 6)
survived2 (446, 2)

In [15]:
pd.concat([passenger2, ticket2]) # concat - 무조건 다 합침

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,193,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
1,192,"Carbines, Mr. William",male,19.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
2,715,"Greenberg, Mr. Samuel",male,52.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,533,"Elias, Mr. Joseph Jr",male,17.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN
4,133,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
440,692,NaN,NaN,NaN,NaN,NaN,349256,3.0,13.4167,NaN,C
441,585,NaN,NaN,NaN,NaN,NaN,3411,3.0,8.7125,NaN,C
442,265,NaN,NaN,NaN,NaN,NaN,382649,3.0,7.7500,NaN,Q
443,328,NaN,NaN,NaN,NaN,NaN,28551,2.0,13.0000,D,S
444,136,NaN,NaN,NaN,NaN,NaN,SC/PARIS 2133,2.0,15.0458,NaN,C

In [16]:
pd.concat([passenger2, ticket2], axis=1)

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked
0,193,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,486.0,4133,3.0,25.4667,NaN,S
1,192,"Carbines, Mr. William",male,19.0,0,0,119.0,PC 17558,1.0,247.5208,B58 B60,C
2,715,"Greenberg, Mr. Samuel",male,52.0,0,0,836.0,PC 17756,1.0,83.1583,E49,C
3,533,"Elias, Mr. Joseph Jr",male,17.0,1,1,528.0,PC 17483,1.0,221.7792,C95,S
4,133,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,396.0,350052,3.0,7.7958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
618,580,"Jussila, Mr. Eiriik",male,32.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
619,503,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
620,538,"LeRoy, Miss. Bertha",female,30.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
621,197,"Mernagh, Mr. Robert",male,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
622,176,"Klasen, Mr. Klas Albin",male,18.0,1,1,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
pd.concat([passenger2, survived2], axis=1)

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Survived
0,193,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,762.0,0.0
1,192,"Carbines, Mr. William",male,19.0,0,0,665.0,1.0
2,715,"Greenberg, Mr. Samuel",male,52.0,0,0,809.0,0.0
3,533,"Elias, Mr. Joseph Jr",male,17.0,1,1,332.0,0.0
4,133,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,21.0,0.0
...,...,...,...,...,...,...,...,...
618,580,"Jussila, Mr. Eiriik",male,32.0,0,0,NaN,NaN
619,503,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,NaN,NaN
620,538,"LeRoy, Miss. Bertha",female,30.0,0,0,NaN,NaN
621,197,"Mernagh, Mr. Robert",male,NaN,0,0,NaN,NaN
622,176,"Klasen, Mr. Klas Albin",male,18.0,1,1,NaN,NaN

# merge - sql의 join 역할과 같음
- inner join이 기본값임 - 겹치는 것만 합침

In [18]:
passenger2.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'SibSp', 'Parch'], dtype='str')

In [19]:
pd.merge(passenger2, ticket2, how="inner", on='PassengerId')

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,192,"Carbines, Mr. William",male,19.0,0,0,28424,2,13.0000,NaN,S
1,715,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,2,13.0000,NaN,S
2,533,"Elias, Mr. Joseph Jr",male,17.0,1,1,2690,3,7.2292,NaN,C
3,133,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,3,14.5000,NaN,S
4,597,"Leitch, Miss. Jessie Wills",female,NaN,0,0,248727,2,33.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
312,349,"Coutts, Master. William Loch ""William""",male,3.0,1,1,C.A. 37671,3,15.9000,NaN,S
313,616,"Herman, Miss. Alice",female,24.0,1,2,220845,2,65.0000,NaN,S
314,580,"Jussila, Mr. Eiriik",male,32.0,0,0,STON/O 2. 3101286,3,7.9250,NaN,S
315,503,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,330909,3,7.6292,NaN,Q
316,176,"Klasen, Mr. Klas Albin",male,18.0,1,1,350404,3,7.8542,NaN,S

In [20]:
len(ticket2)

445

In [21]:
# left join과 같음
pd.merge(passenger2, ticket2, how='left', on='PassengerId')

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,193,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,NaN,NaN,NaN,NaN,NaN
1,192,"Carbines, Mr. William",male,19.0,0,0,28424,2.0,13.0000,NaN,S
2,715,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,2.0,13.0000,NaN,S
3,533,"Elias, Mr. Joseph Jr",male,17.0,1,1,2690,3.0,7.2292,NaN,C
4,133,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,A/5. 3337,3.0,14.5000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
618,580,"Jussila, Mr. Eiriik",male,32.0,0,0,STON/O 2. 3101286,3.0,7.9250,NaN,S
619,503,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,330909,3.0,7.6292,NaN,Q
620,538,"LeRoy, Miss. Bertha",female,30.0,0,0,NaN,NaN,NaN,NaN,NaN
621,197,"Mernagh, Mr. Robert",male,NaN,0,0,NaN,NaN,NaN,NaN,NaN
622,176,"Klasen, Mr. Klas Albin",male,18.0,1,1,350404,3.0,7.8542,NaN,S

In [22]:
# outer join과 같음 - 있는 거 다 합침
pd.merge(passenger2, ticket2, how='outer', on='PassengerId')

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,3.0,7.250,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN
2,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,3.0,7.925,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,1.0,53.100,C123,S
4,5,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,3.0,8.050,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
746,885,NaN,NaN,NaN,NaN,NaN,SOTON/OQ 392076,3.0,7.050,NaN,S
747,886,"Rice, Mrs. William (Margaret Norton)",female,39.0,0.0,5.0,382652,3.0,29.125,NaN,Q
748,887,"Montvila, Rev. Juozas",male,27.0,0.0,0.0,211536,2.0,13.000,NaN,S
749,888,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,1.0,30.000,B42,S
750,891,NaN,NaN,NaN,NaN,NaN,370376,3.0,7.750,NaN,Q

# join
- left_df.join(right_df)
- left join이 기본

In [23]:
passenger2.set_index('PassengerId')
passenger2

,PassengerId,Name,Sex,Age,SibSp,Parch
0,193,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0
1,192,"Carbines, Mr. William",male,19.0,0,0
2,715,"Greenberg, Mr. Samuel",male,52.0,0,0
3,533,"Elias, Mr. Joseph Jr",male,17.0,1,1
4,133,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0
...,...,...,...,...,...,...
618,580,"Jussila, Mr. Eiriik",male,32.0,0,0
619,503,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0
620,538,"LeRoy, Miss. Bertha",female,30.0,0,0
621,197,"Mernagh, Mr. Robert",male,NaN,0,0
622,176,"Klasen, Mr. Klas Albin",male,18.0,1,1

In [24]:
ticket2 = ticket2.set_index('PassengerId')
ticket2

                    Ticket  Pclass      Fare    Cabin Embarked
PassengerId
486                   4133       3   25.4667      NaN        S
119               PC 17558       1  247.5208  B58 B60        C
836               PC 17756       1   83.1583      E49        C
528               PC 17483       1  221.7792      C95        S
396                 350052       3    7.7958      NaN        S
...                    ...     ...       ...      ...      ...
692                 349256       3   13.4167      NaN        C
585                   3411       3    8.7125      NaN        C
265                 382649       3    7.7500      NaN        Q
328                  28551       2   13.0000        D        S
136          SC/PARIS 2133       2   15.0458      NaN        C

[445 rows x 5 columns]

In [26]:
passenger2.join(ticket2)

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,193,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19.0,1,0,NaN,NaN,NaN,NaN,NaN
1,192,"Carbines, Mr. William",male,19.0,0,0,A/5 21171,3.0,7.250,NaN,S
2,715,"Greenberg, Mr. Samuel",male,52.0,0,0,NaN,NaN,NaN,NaN,NaN
3,533,"Elias, Mr. Joseph Jr",male,17.0,1,1,STON/O2. 3101282,3.0,7.925,NaN,S
4,133,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1,0,113803,1.0,53.100,C123,S
...,...,...,...,...,...,...,...,...,...,...,...
618,580,"Jussila, Mr. Eiriik",male,32.0,0,0,A/5. 3336,3.0,16.100,NaN,S
619,503,"O'Sullivan, Miss. Bridget Mary",female,NaN,0,0,230136,2.0,39.000,F4,S
620,538,"LeRoy, Miss. Bertha",female,30.0,0,0,31028,2.0,10.500,NaN,S
621,197,"Mernagh, Mr. Robert",male,NaN,0,0,NaN,NaN,NaN,NaN,NaN
622,176,"Klasen, Mr. Klas Albin",male,18.0,1,1,NaN,NaN,NaN,NaN,NaN

# 중복 여부 확인 및 제거하기
- duplicated().sum() : 중복이 있는 데이터 제거
- drop_duplicates() : 중복 행 제거

In [27]:
toss=pd.read_csv("./data/toss_reviews.csv", index_col=0)
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,5,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,5,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,5,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,5,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
57223,김민,5,"아니 업데이트 방금하니까, 주문수정하는게 가격 바꾸는게 안되네요? 무조건 취소하고 ...",2024년 11월 11일,"안녕하세요 김민님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 정말 죄..."
57224,최고운,5,업데이트 후 동영상 재생광고를 선택권없이 무조건 시청해야 하군요. wi-fi 환경이...,2023년 6월 3일,"안녕하세요. 최고운님. 토스 고객센터입니다. 먼저, 이용에 불편을 드려 죄송합니다...."
57225,블리,5,"라이브쇼핑보고,포인트받기 시스템 변경후,어찌 주구장창 1포인트만 나오는지.........",2024년 4월 11일,"안녕하세요. 블리님, 토스 고객센터입니다. 먼저 서비스 이용에 불편을 드렸다면 대단..."
57226,조명현,5,구석구석 숨어있던 버그를 잡다가 업데이트 설치가 안 되는 버그가 생긴 듯 합니다,2025년 2월 25일,"안녕하세요. 조명현 님, 토스팀입니다. 사용에 불편을 드린것 같아 마음이 무겁습니다..."
57227,이예진,5,홈화면에 계좌 순서 설정한게 반영 안되게 바뀌었는지 이해가 안감 너무 불편함,2025년 2월 27일,"안녕하세요. 이예진 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."

In [28]:
toss[toss['사용자']=='Won Choi']

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
20,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
40,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
60,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
80,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
54642,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
55156,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
55670,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
56184,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
56698,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."

In [29]:
toss.duplicated().sum()

np.int64(56698)

In [30]:
toss=toss.drop_duplicates()
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,5,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,5,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,5,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,5,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
57223,김민,5,"아니 업데이트 방금하니까, 주문수정하는게 가격 바꾸는게 안되네요? 무조건 취소하고 ...",2024년 11월 11일,"안녕하세요 김민님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 정말 죄..."
57224,최고운,5,업데이트 후 동영상 재생광고를 선택권없이 무조건 시청해야 하군요. wi-fi 환경이...,2023년 6월 3일,"안녕하세요. 최고운님. 토스 고객센터입니다. 먼저, 이용에 불편을 드려 죄송합니다...."
57225,블리,5,"라이브쇼핑보고,포인트받기 시스템 변경후,어찌 주구장창 1포인트만 나오는지.........",2024년 4월 11일,"안녕하세요. 블리님, 토스 고객센터입니다. 먼저 서비스 이용에 불편을 드렸다면 대단..."
57226,조명현,5,구석구석 숨어있던 버그를 잡다가 업데이트 설치가 안 되는 버그가 생긴 듯 합니다,2025년 2월 25일,"안녕하세요. 조명현 님, 토스팀입니다. 사용에 불편을 드린것 같아 마음이 무겁습니다..."
57227,이예진,5,홈화면에 계좌 순서 설정한게 반영 안되게 바뀌었는지 이해가 안감 너무 불편함,2025년 2월 27일,"안녕하세요. 이예진 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."

In [31]:
toss = toss.reset_index(drop=True)
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,5,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,5,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,5,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,5,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
525,김민,5,"아니 업데이트 방금하니까, 주문수정하는게 가격 바꾸는게 안되네요? 무조건 취소하고 ...",2024년 11월 11일,"안녕하세요 김민님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 정말 죄..."
526,최고운,5,업데이트 후 동영상 재생광고를 선택권없이 무조건 시청해야 하군요. wi-fi 환경이...,2023년 6월 3일,"안녕하세요. 최고운님. 토스 고객센터입니다. 먼저, 이용에 불편을 드려 죄송합니다...."
527,블리,5,"라이브쇼핑보고,포인트받기 시스템 변경후,어찌 주구장창 1포인트만 나오는지.........",2024년 4월 11일,"안녕하세요. 블리님, 토스 고객센터입니다. 먼저 서비스 이용에 불편을 드렸다면 대단..."
528,조명현,5,구석구석 숨어있던 버그를 잡다가 업데이트 설치가 안 되는 버그가 생긴 듯 합니다,2025년 2월 25일,"안녕하세요. 조명현 님, 토스팀입니다. 사용에 불편을 드린것 같아 마음이 무겁습니다..."
529,이예진,5,홈화면에 계좌 순서 설정한게 반영 안되게 바뀌었는지 이해가 안감 너무 불편함,2025년 2월 27일,"안녕하세요. 이예진 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."