In [1]:
# joblib 이용해서 데이터 불러올 수 있음
import joblib
import pandas as pd

In [2]:
test = pd.read_csv("./data/titanic_test.csv")
test

     Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0           0       3    male  24.0      2      0        S
1           0       3    male  44.0      0      1        S
2           1       3    male  22.0      0      0        C
3           0       3    male  41.0      2      0        S
4           1       3  female   NaN      1      0        Q
..        ...     ...     ...   ...    ...    ...      ...
174         1       2  female  25.0      0      1        S
175         0       3    male  20.0      0      0        S
176         0       2    male  28.0      0      0        S
177         1       2  female  23.0      0      0        C
178         0       2    male  31.0      1      1        S

[179 rows x 7 columns]

In [3]:
test['family'] = test['SibSp'] + test['Parch']
test = test.drop(['SibSp','Parch'], axis=1)
test

     Survived  Pclass     Sex   Age Embarked  family
0           0       3    male  24.0        S       2
1           0       3    male  44.0        S       1
2           1       3    male  22.0        C       0
3           0       3    male  41.0        S       2
4           1       3  female   NaN        Q       1
..        ...     ...     ...   ...      ...     ...
174         1       2  female  25.0        S       1
175         0       3    male  20.0        S       0
176         0       2    male  28.0        S       0
177         1       2  female  23.0        C       0
178         0       2    male  31.0        S       2

[179 rows x 6 columns]

In [4]:
X_test = test.drop("Survived", axis=1)
y_test = test["Survived"]

In [5]:
X_test

     Pclass     Sex   Age Embarked  family
0         3    male  24.0        S       2
1         3    male  44.0        S       1
2         3    male  22.0        C       0
3         3    male  41.0        S       2
4         3  female   NaN        Q       1
..      ...     ...   ...      ...     ...
174       2  female  25.0        S       1
175       3    male  20.0        S       0
176       2    male  28.0        S       0
177       2  female  23.0        C       0
178       2    male  31.0        S       2

[179 rows x 5 columns]

In [6]:
y_test

0      0
1      0
2      1
3      0
4      1
      ..
174    1
175    0
176    0
177    1
178    0
Name: Survived, Length: 179, dtype: int64

# 모델 불러와서 예측하기

In [7]:
model = joblib.load("./data/titanic_best_model.joblib")
print(model)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['Pclass', 'Age', 'family'], dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore'))]),
                                                  Index(['Sex', 'Embarked']...
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=np.float64(0.007122485584859914),
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=2, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=1000, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [8]:
from sklearn.metrics import classification_report, roc_auc_score

In [9]:
pred = model.predict(X_test) # 파이프라인 사용하면 X_test만 가져와서 해주면 됨
print(roc_auc_score(y_test, pred))
print(classification_report(y_test, pred))

0.7507905138339921
              precision    recall  f1-score   support

           0       0.77      0.94      0.85       110
           1       0.85      0.57      0.68        69

    accuracy                           0.79       179
   macro avg       0.81      0.75      0.76       179
weighted avg       0.80      0.79      0.78       179